/* JEU — Dépannages avec bon de travail
   Une seule bonne réponse par étape. La 3e valeur de chaque choix est le résultat (bon choix) ou l'explication (mauvais choix). */
C.diag=[
 {id:"prise-morte",t:"Une prise ne marche plus",ic:"🔌",niv:1,
  bon:{lieu:"Maison individuelle — chambre 2",qui:"Mme Martin, propriétaire",heure:"Mardi 9 h 10",prio:2,pb:"La prise près du bureau ne fonctionne plus. Les autres prises de la chambre marchent.",contrainte:"Enfant malade à la maison : intervention rapide et propre."},
  etapes:[
   {q:"Tu arrives. Que fais-tu en premier ?",o:[["Je questionne la cliente : depuis quand, que s'est-il passé, qu'est-ce qui était branché ?",true,"Elle explique qu'un radiateur d'appoint était branché sur une multiprise, qu'il y a eu une odeur de brûlé, puis plus rien."],["Je démonte tout de suite la prise",false,"On ne démonte rien sans savoir et sans couper : d'abord on écoute et on observe."],["Je change le disjoncteur du circuit",false,"Changer une pièce au hasard n'est pas du dépannage. Les autres prises du même circuit marchent : le disjoncteur n'y est pour rien."]]},
   {q:"Avant d'ouvrir la prise, tu…",o:[["Identifies le circuit, coupes son disjoncteur, le condamnes et vérifies l'absence de tension au VAT",true,"Le VAT, testé avant et après, confirme : plus de tension sur la prise. Tu peux travailler."],["Coupes le disjoncteur et tu y vas sans vérifier",false,"Sans VAT, tu ne sais pas si tu as coupé le bon circuit. Et sans condamnation, quelqu'un peut le réarmer."],["Travailles sous tension avec des gants",false,"Pour un remplacement, on travaille hors tension. Le travail sous tension est une spécialité à part."]]},
   {info:"La borne de la phase est noircie, l'isolant du fil marron a fondu sur 5 mm, la vis est desserrée.",q:"Que s'est-il passé ?",o:[["Un mauvais serrage a fait chauffer la connexion jusqu'à la couper",true,"Exact : un contact desserré crée une résistance, qui chauffe (P = R × I²). Avec un radiateur de 2 000 W, la borne a fini par brûler."],["Un défaut de terre",false,"La terre n'est pas en cause : c'est la borne de phase qui a chauffé."],["Une surtension du réseau",false,"Une surtension aurait touché plusieurs appareils. Ici, les traces sont sur une seule borne."]]},
   {q:"Comment répares-tu ?",o:[["Je recoupe le fil abîmé jusqu'au cuivre sain, je redénude et je pose une prise neuve bien serrée",true,"Le fil est sain après recoupe ; la nouvelle prise est serrée, tu tires sur chaque fil pour vérifier."],["Je remets la même prise en resserrant la vis",false,"Une borne qui a chauffé est abîmée (ressort détrempé, plastique fragilisé) : on la remplace."],["Je mets du ruban isolant sur le fil fondu",false,"Un isolant fondu ne se répare pas avec du ruban : on recoupe jusqu'au fil sain."]]},
   {q:"Avant de partir, tu…",o:[["Remets sous tension, testes la prise (tension, terre) et conseilles de brancher le radiateur directement sur une prise murale",true,"Testeur de prise : phase, neutre et terre OK. La cliente sait maintenant pourquoi éviter les multiprises pour le chauffage."],["Pars sans tester, la prise est neuve",false,"On essaie toujours après une réparation."],["Remplaces le disjoncteur 16 A par un 20 A pour éviter que ça recommence",false,"Jamais : le calibre dépend de la section du câble. Augmenter le calibre, c'est risquer l'incendie."]]}],
  fin:"La panne venait d'une connexion mal serrée sur la phase. Avec un radiateur de 2 000 W branché longtemps, la borne a chauffé jusqu'à brûler et couper le circuit. Réparation : recoupe du conducteur, prise neuve, serrage contrôlé, essai et conseil à la cliente.",
  retenir:"Un mauvais serrage = une résistance = de la chaleur. Une borne noircie se remplace toujours."},

 {id:"bouilloire",t:"Le disjoncteur saute dès qu'on allume la bouilloire",ic:"☕",niv:1,
  bon:{lieu:"Appartement — cuisine",qui:"Étudiant locataire",heure:"Dimanche 10 h",prio:2,pb:"Le disjoncteur des prises de la cuisine déclenche immédiatement, avec un petit claquement, quand on allume la bouilloire.",contrainte:"Petit budget."},
  etapes:[
   {q:"Un déclenchement instantané avec claquement, c'est plutôt…",o:[["Un court-circuit (déclenchement magnétique)",true,"Le court-circuit fait monter le courant à des centaines d'ampères : la partie magnétique coupe en quelques millisecondes."],["Une surcharge",false,"Une surcharge fait déclencher la partie thermique, au bout de plusieurs secondes ou minutes."],["Un défaut à la terre",false,"Un défaut à la terre fait déclencher le différentiel, pas le disjoncteur."]]},
   {q:"Pour savoir si c'est l'appareil ou l'installation :",o:[["Je branche la bouilloire sur un autre circuit, et un autre appareil sur la prise de la cuisine",true,"La bouilloire fait sauter l'autre circuit aussi ; un grille-pain marche sur la prise de la cuisine. Le problème suit la bouilloire."],["Je démonte la prise de la cuisine",false,"Possible, mais un test simple d'abord : échanger les appareils (substitution)."],["Je remplace le disjoncteur",false,"Le disjoncteur fait son travail : il détecte un court-circuit."]]},
   {q:"Confirmation hors tension, à l'ohmmètre, entre les deux broches de la fiche (interrupteur de la bouilloire sur marche) :",o:[["0,2 Ω : court-circuit dans l'appareil",true,"Une bouilloire de 2 200 W devrait mesurer environ 24 Ω (R = U² ÷ P = 230² ÷ 2 200). 0,2 Ω = court-circuit."],["24 Ω : c'est normal",false,"24 Ω serait la valeur d'une bouilloire en bon état. Ici l'appareil mesure 0,2 Ω."],["Infini : c'est normal",false,"Infini, interrupteur sur marche, voudrait dire résistance coupée : la bouilloire ne chaufferait pas, sans court-circuit."]]},
   {q:"Conclusion pour le client :",o:[["La bouilloire est en court-circuit et ne doit plus être utilisée. L'installation est saine.",true,"Le disjoncteur a bien protégé le câble. Aucune réparation sur l'installation."],["Mettre un disjoncteur 32 A",false,"Jamais : le circuit en 2,5 mm² est protégé en 20 A. Et un court-circuit ferait sauter n'importe quel calibre."],["Réparer la bouilloire avec du ruban adhésif",false,"Un appareil en court-circuit est dangereux : on ne le bricole pas."]]}],
  fin:"Court-circuit interne de la bouilloire (0,2 Ω au lieu d'environ 24 Ω). Installation saine, disjoncteur fonctionnel. Appareil à jeter.",
  retenir:"Magnétique (instantané) = court-circuit. Thermique (après un moment) = surcharge. Différentiel = fuite à la terre."},

 {id:"tout-noir",t:"Plus rien ne marche dans la maison",ic:"🌑",niv:1,
  bon:{lieu:"Maison — tableau dans le garage",qui:"Mme Diallo",heure:"Samedi 19 h 30",prio:1,pb:"Tout s'est coupé pendant que le four, le lave-linge et le sèche-linge tournaient.",contrainte:"Repas en cours, la cliente est stressée."},
  etapes:[
   {q:"Tu commences par…",o:[["Regarder ce qui a déclenché : disjoncteur de branchement, différentiels, disjoncteurs",true,"Les disjoncteurs du tableau sont enclenchés. Le disjoncteur de branchement, près du compteur, est déclenché."],["Appeler le distributeur pour une coupure réseau",false,"Avant d'appeler, on regarde : les voisins ont-ils du courant ? Qu'est-ce qui a déclenché ?"],["Remplacer le disjoncteur de branchement",false,"Il appartient au réseau public : l'électricien ne le remplace pas, il peut seulement le réarmer."]]},
   {q:"Le disjoncteur de branchement a sauté avec beaucoup d'appareils en route. Hypothèse la plus probable ?",o:[["Dépassement de la puissance de l'abonnement",true,"Four (3 kW) + lave-linge (2 kW) + sèche-linge (2,5 kW) + le reste : on dépasse les 6 kVA de l'abonnement."],["Un court-circuit dans le four",false,"Un court-circuit ferait déclencher le disjoncteur du four, qui est resté enclenché."],["La foudre",false,"Pas d'orage, et la coupure coïncide avec la mise en route des appareils."]]},
   {q:"6 kVA en 230 V, c'est environ…",o:[["26 A (disjoncteur de branchement réglé à 30 A)",true,"I = 6 000 ÷ 230 ≈ 26 A : réglage 30 A pour un abonnement 6 kVA."],["60 A",false,"60 A correspond à un abonnement de 12 kVA."],["6 A",false,"6 kVA = 6 000 VA ; divisé par 230 V, ça fait environ 26 A."]]},
   {q:"Que proposes-tu ?",o:[["Étaler l'utilisation des gros appareils, augmenter l'abonnement ou installer un délesteur",true,"Tu réarmes, tout repart. Un délesteur couperait automatiquement le chauffe-eau ou le chauffage à l'approche de la limite."],["Régler soi-même le disjoncteur de branchement plus haut",false,"Le réglage est plombé par le distributeur : il ne change qu'avec l'abonnement."],["Supprimer le circuit du sèche-linge",false,"Le problème n'est pas le circuit mais la puissance appelée en même temps."]]}],
  fin:"Déclenchement du disjoncteur de branchement par dépassement de la puissance souscrite. Aucun défaut sur l'installation. Conseils : délestage, étalement des usages ou abonnement supérieur.",
  retenir:"Disjoncteur de branchement = limite de l'abonnement + protection différentielle 500 mA de toute l'installation."},

 {id:"led-lueur",t:"Les spots LED luisent quand ils sont éteints",ic:"✨",niv:1,
  bon:{lieu:"Appartement rénové — séjour",qui:"Mme Nguyen",heure:"Jeudi 18 h",prio:3,pb:"Les spots LED du séjour restent légèrement allumés quand l'interrupteur est sur arrêt.",contrainte:"Aucune."},
  etapes:[
   {q:"Une lueur des LED éteintes peut venir de…",o:[["Un interrupteur qui coupe le neutre, un interrupteur à voyant, ou un courant induit entre câbles",true,"Bonne liste. On commence par vérifier la plus dangereuse : un interrupteur qui couperait le neutre."],["Des LED de mauvaise qualité, uniquement",false,"Possible, mais on vérifie d'abord le câblage : une erreur peut être dangereuse."],["Un problème de terre",false,"La terre n'alimente pas les spots."]]},
   {q:"Interrupteur sur arrêt, tu mesures à la douille d'un spot : 230 V entre une borne et la terre. Conclusion ?",o:[["La phase arrive en permanence sur le spot : l'interrupteur coupe le neutre",true,"Lampe « éteinte » mais sous tension : danger pour qui change un spot."],["C'est normal",false,"Interrupteur ouvert, aucun conducteur du spot ne devrait être sous tension par rapport à la terre."],["Le VAT est en panne",false,"Tu l'as testé avant et après sur une source connue : il fonctionne."]]},
   {q:"Correction :",o:[["Consigner, puis recâbler : la phase passe par l'interrupteur, le neutre va directement aux spots",true,"Après correction : interrupteur sur arrêt, plus aucune tension sur les spots, plus de lueur."],["Ajouter un deuxième interrupteur sur la phase",false,"Ça complique sans corriger : un seul interrupteur, sur la phase."],["Changer les spots",false,"Les spots ne sont pas en cause : c'est le câblage."]]},
   {q:"S'il restait une petite lueur après correction, ce serait probablement…",o:[["Un courant induit ou un interrupteur à voyant : interrupteur sans voyant, ou module anti-lueur",true,"Les LED consomment si peu qu'un tout petit courant suffit à les faire luire."],["Un court-circuit",false,"Un court-circuit ferait déclencher le disjoncteur."],["Une surcharge",false,"Les LED consomment très peu."]]}],
  fin:"Interrupteur câblé sur le neutre : spots sous tension en permanence (risque d'électrisation au remplacement) et lueur des LED. Recâblage pour couper la phase.",
  retenir:"L'interrupteur coupe TOUJOURS la phase."},

 {id:"diff-pluie",t:"Le différentiel saute quand il pleut",ic:"🌧️",niv:2,
  bon:{lieu:"Pavillon — garage et jardin",qui:"M. Leroy",heure:"Lundi 14 h",prio:2,pb:"Un des différentiels 30 mA déclenche quand il pleut. Il se réarme le lendemain.",contrainte:"Le congélateur du garage est sur ce différentiel."},
  etapes:[
   {q:"Un différentiel qui déclenche quand il pleut, ça fait penser à…",o:[["Un défaut d'isolement lié à l'humidité (fuite vers la terre)",true,"L'eau rend un isolant conducteur : le courant fuit vers la terre, le différentiel le détecte et coupe."],["Une surcharge",false,"Une surcharge fait déclencher un disjoncteur, pas un différentiel. Et la pluie n'ajoute pas d'appareils."],["Un différentiel trop sensible à remplacer par un 300 mA",false,"Interdit : le 30 mA protège les personnes. On cherche le défaut."]]},
   {q:"Le différentiel alimente 6 circuits. Comment trouver le circuit fautif ?",o:[["Couper tous les disjoncteurs en aval, réarmer le différentiel, puis remonter les disjoncteurs un par un",true,"Quand tu remontes le circuit « prises extérieures et éclairage du jardin », le différentiel déclenche. Tu tiens le circuit."],["Débrancher tous les appareils de la maison",false,"Ça peut aider, mais le défaut peut venir du câblage, pas d'un appareil."],["Attendre qu'il pleuve",false,"On trouve le circuit par élimination, sans attendre la pluie."]]},
   {q:"Sur ce circuit : 2 prises extérieures et 3 bornes lumineuses. Comment confirmer le défaut ?",o:[["Consigner et mesurer l'isolement au mégohmmètre (500 V) entre conducteurs actifs et terre",true,"Résultat : 0,08 MΩ. Beaucoup trop bas : le minimum est de 0,5 MΩ."],["Mesurer la tension à la prise au multimètre",false,"La tension serait normale : le multimètre ne voit pas une fuite. Il faut un mégohmmètre."],["Appuyer sur le bouton test du différentiel",false,"Il vérifie le différentiel, pas le circuit. Le différentiel fonctionne : il fait son travail."]]},
   {info:"En déconnectant les bornes une par une, le défaut disparaît quand tu isoles la borne du fond. Dedans : de l'eau, un joint craquelé, des connexions vertes d'oxydation.",q:"Quelle est la cause ?",o:[["Un défaut d'étanchéité : l'eau entre et crée une fuite vers la terre",true,"Le luminaire n'a plus l'indice de protection IP d'origine : il doit être remplacé par un modèle adapté à l'extérieur."],["Un fil de terre trop gros",false,"La section de la terre n'a rien à voir avec une infiltration d'eau."],["Un problème de neutre",false,"Le défaut se mesure entre conducteurs actifs et terre, et la cause est visible : l'eau dans le boîtier."]]},
   {q:"Ta réparation :",o:[["Remplacer la borne par un modèle à l'indice IP adapté, avec connexions étanches, puis remesurer l'isolement",true,"Après remplacement : isolement supérieur à 200 MΩ. Le différentiel tient ; tu le testes avec son bouton."],["Mettre du silicone sur le joint",false,"Bricolage provisoire : un matériel qui a pris l'eau est remplacé."],["Déplacer le circuit sur un autre différentiel",false,"Le défaut serait toujours là : il ferait sauter l'autre différentiel, avec d'autres circuits en plus."]]}],
  fin:"Défaut d'isolement par infiltration d'eau dans une borne de jardin. Méthode : hypothèse (humidité), recherche du circuit par élimination, mesure d'isolement, recherche du récepteur en défaut, remplacement par du matériel à l'indice IP adapté, nouvelle mesure, essais.",
  retenir:"Différentiel qui déclenche = fuite vers la terre. On la cherche par élimination puis au mégohmmètre."},

 {id:"va-et-vient",t:"Le va-et-vient du couloir fait n'importe quoi",ic:"💡",niv:2,
  bon:{lieu:"Appartement neuf — couloir",qui:"Chef de chantier",heure:"Jeudi 10 h",prio:2,pb:"La lumière du couloir ne s'allume que si l'interrupteur de l'entrée est en position haute. Celui du fond ne commande rien dans l'autre position.",contrainte:"Réception du chantier demain matin."},
  etapes:[
   {q:"Le premier réflexe avant de démonter :",o:[["Consigner le circuit d'éclairage et vérifier l'absence de tension",true,"Disjoncteur 16 A du couloir coupé, cadenassé, VAT : pas de tension."],["Démonter sous tension pour mesurer en même temps",false,"On démonte hors tension."],["Changer les deux interrupteurs",false,"Ils sont neufs : on cherche d'abord l'erreur de câblage."]]},
   {q:"Rappel : dans un va-et-vient, où arrive la phase ?",o:[["Sur la borne commune du premier va-et-vient",true,"Le commun du 2e va-et-vient part vers la lampe ; les deux autres bornes reçoivent les navettes."],["Sur une borne de navette",false,"La phase arrive sur le commun, sinon l'interrupteur ne peut plus « choisir » la navette."],["Directement sur la lampe",false,"La lampe reçoit le retour lampe, depuis le commun du 2e interrupteur."]]},
   {info:"Au fond du couloir, le retour lampe arrive sur une borne de navette, et une navette arrive sur la borne commune.",q:"Conséquence ?",o:[["Le montage ne fonctionne que dans certaines positions : c'est exactement le symptôme",true,"Commun et navette inversés : l'interrupteur du fond ne fait plus son travail."],["Un court-circuit",false,"Il n'y a pas de liaison phase-neutre : pas de court-circuit, juste un montage faux."],["Rien, les bornes sont équivalentes",false,"Le commun est différent des deux bornes de navettes ; il est repéré (L, ou une couleur de vis)."]]},
   {q:"Après correction, avant de refermer :",o:[["Vérifier les serrages et tester les 4 combinaisons des deux interrupteurs",true,"Chaque interrupteur change l'état de la lampe, dans toutes les positions."],["Refermer directement",false,"Toujours essayer : c'est la seule preuve que le montage est bon."],["Remplacer par un télérupteur",false,"Inutile : avec 2 points de commande, un va-et-vient bien câblé convient."]]}],
  fin:"Erreur de câblage : commun et navette inversés sur le 2e va-et-vient. Correction, contrôle des serrages, essai des 4 combinaisons.",
  retenir:"Va-et-vient : phase sur le commun du 1er, retour lampe sur le commun du 2e, navettes entre les deux."},

 {id:"minuterie",t:"L'escalier reste allumé jour et nuit",ic:"🏢",niv:2,
  bon:{lieu:"Petit immeuble — cage d'escalier",qui:"Syndic de copropriété",heure:"Mercredi 8 h 45",prio:2,pb:"Les lumières de l'escalier restent allumées en permanence depuis hier, même sans appuyer sur les boutons.",contrainte:"Passage des habitants : garder un éclairage."},
  etapes:[
   {q:"L'éclairage d'un escalier commandé par des boutons à chaque étage, c'est en général…",o:[["Une minuterie (ou un télérupteur) au tableau des parties communes",true,"Au tableau, tu trouves une minuterie modulaire : son voyant est allumé en continu."],["Un va-et-vient",false,"Un va-et-vient ne permet que 2 points de commande."],["Un variateur",false,"Un variateur règle l'intensité lumineuse : ce n'est pas le montage d'un escalier."]]},
   {q:"Le sélecteur de la minuterie est bien sur « auto ». Première vérification simple ?",o:[["Chercher un bouton poussoir resté enfoncé ou bloqué",true,"Au 2e étage, un bouton est enfoncé et coincé : son mécanisme est cassé."],["Remplacer toutes les ampoules",false,"Les ampoules s'allument : elles fonctionnent."],["Mesurer la prise de terre",false,"La terre n'intervient pas dans la commande d'une minuterie."]]},
   {q:"Pour changer le bouton poussoir :",o:[["Consigner le circuit, vérifier l'absence de tension et remplacer le bouton à l'identique",true,"Le nouveau bouton est posé. Depuis chaque étage, la minuterie démarre et s'arrête après le temps réglé."],["Le remplacer sous tension, ce n'est qu'un bouton",false,"Un bouton poussoir de minuterie est alimenté en 230 V : on consigne."],["Le shunter en attendant",false,"Shunter un bouton laisserait l'éclairage allumé en permanence."]]},
   {q:"Les boutons poussoirs lumineux (à voyant) peuvent aussi faire « coller » une minuterie. Pourquoi ?",o:[["Le petit courant des voyants peut suffire à maintenir la commande s'il y en a trop",true,"Les fabricants limitent le nombre de boutons lumineux par minuterie (ou prévoient un raccordement spécial)."],["Ils font sauter le disjoncteur",false,"Ils consomment quelques milliampères."],["Ils créent une fuite à la terre",false,"Leur courant passe par le circuit de commande, pas par la terre."]]}],
  fin:"Bouton poussoir mécaniquement bloqué au 2e étage, qui maintenait la commande de la minuterie. Remplacement à l'identique, essai depuis chaque étage. Information au syndic sur la limite de boutons lumineux.",
  retenir:"Minuterie ou télérupteur qui « colle » : d'abord un bouton bloqué ou trop de boutons lumineux."},

 {id:"chauffe-eau",t:"Plus d'eau chaude le matin",ic:"🚿",niv:2,
  bon:{lieu:"Appartement — chauffe-eau électrique 200 L",qui:"M. Petit, locataire",heure:"Mardi 11 h",prio:2,pb:"Plus d'eau chaude depuis 3 jours. Le chauffe-eau fonctionne en heures creuses.",contrainte:"Le locataire part en déplacement ce soir."},
  etapes:[
   {q:"Le contacteur jour/nuit a un sélecteur à 3 positions. Lesquelles ?",o:[["Auto (heures creuses) / 0 (arrêt) / I (marche forcée)",true,"Le sélecteur est sur Auto. D'après le locataire, le voyant du contacteur ne s'allume jamais la nuit."],["Été / Hiver / Vacances",false,"Ce sont des modes de thermostat, pas d'un contacteur."],["16 A / 20 A / 32 A",false,"Ce sont des calibres de disjoncteurs."]]},
   {q:"Test rapide pour savoir si le chauffe-eau lui-même chauffe :",o:[["Passer en marche forcée et mesurer le courant à la pince",true,"En marche forcée : 10,4 A. Le chauffe-eau chauffe (2 400 W ÷ 230 V ≈ 10,4 A). Résistance et thermostat sont bons."],["Démonter la résistance",false,"Trop tôt : un test simple montre qu'elle fonctionne."],["Vidanger le chauffe-eau",false,"Ça ne dit rien sur le fonctionnement électrique."]]},
   {q:"Il chauffe en marche forcée mais pas en auto. Le problème est donc…",o:[["Dans la commande heures creuses (circuit 2 A, contact du compteur, bobine du contacteur)",true,"Le contacteur ne reçoit pas l'ordre de la nuit."],["Dans la résistance",false,"Elle chauffe en marche forcée : elle est bonne."],["Dans le groupe de sécurité",false,"C'est une pièce de plomberie, sans rapport avec la commande."]]},
   {info:"Le disjoncteur 2 A de commande est déclenché. Hors tension, tu mesures la bobine du contacteur : 0,8 Ω (au lieu de plusieurs centaines d'ohms).",q:"Pourquoi le 2 A a-t-il sauté ?",o:[["La bobine du contacteur est en court-circuit : le contacteur est à changer",true,"À la prochaine commande, le 2 A aurait de nouveau déclenché. Tu remplaces le contacteur à l'identique."],["Le 2 A est trop petit, je mets un 10 A",false,"Le 2 A protège un fil de commande et une bobine : il a déclenché à cause d'un vrai défaut."],["C'est normal",false,"0,8 Ω sur une bobine 230 V, c'est un court-circuit."]]},
   {q:"Après remplacement :",o:[["Essai en marche forcée, vérification de la commande heures creuses, puis sélecteur remis sur Auto",true,"Le locataire vérifiera le lendemain matin. Sélecteur sur Auto : le chauffe-eau chauffera en heures creuses."],["Laisser en marche forcée pour être tranquille",false,"Le chauffe-eau chaufferait aussi en heures pleines : plus cher pour le client."],["Ne rien vérifier",false,"Toujours essayer."]]}],
  fin:"Bobine du contacteur jour/nuit en court-circuit, qui faisait déclencher le disjoncteur 2 A de commande. Remplacement du contacteur, essais, sélecteur remis sur Auto.",
  retenir:"Pas d'eau chaude : la marche forcée sépare en 10 secondes un problème de chauffe-eau d'un problème de commande."},

 {id:"lave-linge",t:"Des picotements en touchant le lave-linge",ic:"🧺",niv:2,
  bon:{lieu:"Maison de 1975 — buanderie",qui:"Mme Robert",heure:"Jeudi 16 h",prio:1,pb:"En touchant le lave-linge et le robinet en même temps, la cliente sent des picotements.",contrainte:"Enfants dans la maison."},
  etapes:[
   {q:"Picotements entre un appareil et un robinet. Hypothèse ?",o:[["La carcasse du lave-linge est sous tension (défaut) et n'est pas correctement reliée à la terre",true,"Une masse sous tension et une terre absente ou mauvaise : le courant cherche un chemin… par la personne."],["De l'électricité statique",false,"La statique donne une décharge unique, pas des picotements répétés au même endroit."],["L'eau est trop calcaire",false,"Aucun rapport avec un risque électrique."]]},
   {q:"Tu mesures la tension entre la carcasse et le robinet :",o:[["Avec un multimètre CAT III et des EPI, sans toucher les parties métalliques",true,"Résultat : 87 V. C'est dangereux : tu fais couper le circuit et débrancher la machine tout de suite."],["En touchant pour sentir",false,"Jamais : on ne teste pas l'électricité avec son corps."],["À l'ohmmètre",false,"Un ohmmètre ne s'utilise jamais sous tension."]]},
   {info:"Au tableau : pas de différentiel 30 mA sur ce circuit. Sur la prise : la terre n'est pas raccordée.",q:"Pourquoi rien n'a coupé ?",o:[["Sans terre, le courant de défaut ne s'écoule pas, et sans 30 mA rien ne détecte la fuite",true,"Il faut à la fois une terre et un différentiel 30 mA."],["Parce que 87 V, c'est de la très basse tension",false,"La TBT, c'est 50 V maximum. 87 V est dangereux."],["Parce que le lave-linge est de classe II",false,"Un lave-linge à carcasse métallique est de classe I : il doit être relié à la terre."]]},
   {q:"La prise de terre de la maison mesure 280 Ω. Que proposes-tu ?",o:[["Améliorer la terre (piquet supplémentaire), raccorder la terre à la prise, ajouter un différentiel 30 mA, et faire réparer le lave-linge",true,"Piquet supplémentaire : 45 Ω. Prise raccordée à la terre et protégée par un 30 mA type A."],["Juste changer le lave-linge",false,"Le prochain défaut serait aussi dangereux : l'installation ne protège pas."],["Relier la terre de la prise au neutre",false,"Interdit en schéma TT, et très dangereux si le neutre se coupe."]]},
   {q:"Essai final :",o:[["Continuité de la terre jusqu'à la prise et test du différentiel au contrôleur (seuil et temps)",true,"Continuité : 0,4 Ω. Le différentiel déclenche à 22 mA en 28 ms. Les personnes sont protégées."],["Appuyer une fois sur le bouton test",false,"Il ne vérifie ni la valeur de déclenchement ni la continuité de la terre."],["Aucun essai",false,"Après une mise en sécurité, on contrôle toujours."]]}],
  fin:"Défaut d'isolement du lave-linge + prise sans terre + prise de terre trop résistante + pas de 30 mA. Mise en sécurité : piquet supplémentaire (45 Ω), raccordement de la terre, différentiel 30 mA type A, contrôles. Lave-linge à faire réparer.",
  retenir:"Protection des personnes = une bonne terre + un différentiel 30 mA. Les deux ensemble."},

 {id:"radiateurs",t:"Le disjoncteur du séjour saute au bout de 20 minutes",ic:"🔥",niv:2,
  bon:{lieu:"Maison — séjour",qui:"M. et Mme Ferrand",heure:"Lundi 18 h",prio:2,pb:"En hiver, le disjoncteur des prises du séjour saute environ 20 minutes après qu'on allume les deux radiateurs d'appoint.",contrainte:"Les clients veulent garder le chauffage."},
  etapes:[
   {q:"Un déclenchement au bout de 20 minutes, c'est…",o:[["La partie thermique : une surcharge",true,"Le thermique laisse passer une petite surcharge un moment, puis coupe avant que le câble ne chauffe trop."],["La partie magnétique : un court-circuit",false,"Un court-circuit déclenche instantanément."],["Le différentiel",false,"C'est le disjoncteur qui déclenche, pas le différentiel."]]},
   {q:"Inventaire : 2 radiateurs de 1 500 W, une TV (150 W), une box et un ordinateur (250 W), un aquarium (100 W). Intensité totale ?",o:[["Environ 15,2 A",true,"P = 3 500 W ; I = 3 500 ÷ 230 ≈ 15,2 A."],["Environ 3,5 A",false,"3 500 W ÷ 230 V ≈ 15,2 A."],["Environ 35 A",false,"Attention à l'ordre de grandeur : 3 500 ÷ 230 ≈ 15,2 A."]]},
   {q:"Le circuit est en 1,5 mm² protégé par un 16 A. Avec 15,2 A en continu…",o:[["On est à la limite : le thermique déclenche, et c'est lui qui protège le câble",true,"Le disjoncteur fait exactement son travail."],["Il faut mettre un 20 A sur le même câble",false,"Un 1,5 mm² ne se protège jamais en 20 A."],["Le disjoncteur est défectueux",false,"Le calcul montre que la charge est trop forte."]]},
   {q:"La bonne solution :",o:[["Créer un circuit dédié au chauffage, dimensionné pour sa puissance",true,"Un circuit chauffage en 1,5 mm² / 16 A (jusqu'à 3 500 W) pour les radiateurs, séparé des prises. Idéalement des radiateurs fixes à fil pilote."],["Brancher un radiateur sur une multiprise dans la cuisine",false,"On déplace le problème, et les multiprises ne sont pas faites pour du chauffage."],["Garder le même circuit et ne plus regarder la TV",false,"Ce n'est pas une solution durable : le chauffage doit avoir son circuit."]]}],
  fin:"Surcharge du circuit prises (environ 15 A permanents sur un 16 A) due à deux radiateurs d'appoint. Proposition : circuit chauffage dédié et radiateurs fixes.",
  retenir:"Ib ≤ In ≤ Iz : le besoin, puis la protection, puis la capacité du câble."},

 {id:"volet",t:"Le volet monte mais ne descend plus",ic:"🪟",niv:2,
  bon:{lieu:"Maison — volet roulant du salon",qui:"M. Bernard",heure:"Vendredi 17 h",prio:3,pb:"Le volet monte bien, mais ne descend plus depuis les travaux de décoration de la semaine dernière.",contrainte:"Le client doit pouvoir fermer ce soir."},
  etapes:[
   {q:"Un moteur de volet roulant filaire a 4 fils. Lesquels ?",o:[["Neutre, montée, descente, terre",true,"Le neutre est commun ; l'inverseur envoie la phase sur le fil de montée ou sur celui de descente."],["Phase, neutre, terre et fil pilote",false,"Le fil pilote, c'est pour les radiateurs."],["Deux phases et deux neutres",false,"Un neutre commun, deux fils de commande et la terre."]]},
   {q:"Le volet monte : moteur et neutre sont sans doute bons. Que mesures-tu ?",o:[["À l'inverseur, touche « descente » appuyée : la tension entre le fil de descente et le neutre",true,"230 V : l'inverseur envoie bien la phase sur le fil de descente."],["La résistance de la terre",false,"La terre ne fait pas tourner le moteur."],["La tension sur le fil de montée",false,"La montée marche : c'est la descente qu'il faut suivre."]]},
   {q:"Au boîtier près du coffre, touche « descente » appuyée : 0 V sur le fil de descente. Conclusion ?",o:[["Le fil de descente est coupé entre l'inverseur et le coffre",true,"Le défaut est entre deux points de mesure : 230 V d'un côté, 0 V de l'autre."],["Le moteur est grillé",false,"Le moteur ne reçoit même pas la tension : on ne peut pas l'accuser."],["L'inverseur est hors service",false,"L'inverseur envoie bien 230 V."]]},
   {info:"En suivant le câble, tu trouves une vis de la nouvelle baguette décorative plantée dans le câble.",q:"Réparation :",o:[["Consigner, couper la partie abîmée et reconnecter dans une boîte de dérivation accessible (ou remplacer le tronçon)",true,"Boîte posée et accessible, bornes automatiques. Tu préviens le client du danger : la vis aurait pu toucher la phase permanente."],["Entourer le câble de ruban adhésif",false,"Le conducteur est coupé : il faut refaire la connexion."],["Faire passer un fil volant le long du mur",false,"Une installation fixe se fait avec des câbles protégés et fixés."]]},
   {q:"Essai :",o:[["Montée, descente et arrêts en fin de course",true,"Tout fonctionne."],["Seulement la descente",false,"On teste toutes les fonctions après une intervention."],["Aucun",false,"Toujours essayer."]]}],
  fin:"Conducteur de descente sectionné par une vis lors de travaux de décoration. Localisation par mesures successives (230 V à l'inverseur, 0 V au coffre), réparation dans une boîte accessible, essai complet.",
  retenir:"Dépanner, c'est mesurer de point en point jusqu'à l'endroit où la tension disparaît."},

 {id:"consuel",t:"Le Consuel refuse l'attestation",ic:"📋",niv:3,
  bon:{lieu:"Maison neuve — fin de chantier",qui:"Ton chef d'entreprise",heure:"Mercredi 9 h",prio:2,pb:"Le contrôleur du Consuel a relevé des non-conformités : elles doivent être corrigées avant le visa.",contrainte:"Le client emménage dans 10 jours."},
  etapes:[
   {info:"Non-conformité n°1 : « Prise de courant 16 A située dans le volume 2 de la salle de bain ».",q:"Que fais-tu ?",o:[["Je déplace la prise hors volume (ou je la remplace par une prise rasoir à transformateur de séparation)",true,"La prise est déplacée à plus de 0,60 m du bord de la douche."],["Je mets un cache sur la prise",false,"Une prise interdite reste interdite, même cachée."],["Je la laisse, elle est protégée par le 30 mA",false,"Le 30 mA est obligatoire en plus : il ne rend pas une prise 16 A admissible dans le volume 2."]]},
   {info:"Non-conformité n°2 : « Points d'éclairage sans DCL ».",q:"Que fais-tu ?",o:[["J'installe un DCL à chaque point d'éclairage (plafond et appliques)",true,"Le client pourra raccorder ses luminaires sans toucher aux fils."],["Je laisse des dominos au plafond",false,"Les DCL sont exigés dans les logements : le domino n'est pas un dispositif de connexion pour luminaire."],["Je pose moi-même des luminaires définitifs",false,"Le DCL reste exigé : il permet de changer de luminaire en sécurité."]]},
   {info:"Non-conformité n°3 : « Circuit plaque de cuisson protégé par un différentiel de type AC ».",q:"Que fais-tu ?",o:[["Je déplace le circuit sur un différentiel de type A",true,"La plaque à induction peut produire des fuites avec composante continue : le type A est exigé."],["Je remplace le disjoncteur 32 A par un 40 A",false,"Aucun rapport : c'est le type du différentiel qui est en cause."],["Je supprime le différentiel de ce circuit",false,"Tous les circuits doivent être protégés par un différentiel 30 mA."]]},
   {info:"Non-conformité n°4 : « Tableau sans repérage des circuits ».",q:"Que fais-tu ?",o:[["Je repère chaque circuit au tableau et je joins le schéma unifilaire",true,"Le client et les futurs dépanneurs sauront couper le bon circuit."],["J'écris « électricité » sur la porte",false,"Chaque circuit doit être identifié."],["Rien, le client saura bien",false,"Le repérage est obligatoire."]]},
   {q:"Une fois tout corrigé :",o:[["Je refais l'autocontrôle (mesures) et je renvoie l'attestation pour visa",true,"Le Consuel vise l'attestation : le distributeur peut mettre l'installation en service."],["Je mets en service moi-même",false,"La mise en service par le distributeur se fait après le visa de l'attestation."],["J'attends que le client s'en occupe",false,"C'est à l'installateur de corriger et de renvoyer l'attestation."]]}],
  fin:"Quatre non-conformités corrigées : prise hors volume, DCL posés, plaque sur différentiel type A, repérage et schéma. Autocontrôle refait, attestation renvoyée pour visa.",
  retenir:"Volumes, DCL, type A pour la plaque et le lave-linge, repérage : les grands classiques du contrôle de conformité."},

 {id:"neutre-atelier",t:"Des appareils grillés dans l'atelier",ic:"⚡",niv:3,
  bon:{lieu:"Atelier de menuiserie — triphasé 400 V + neutre",qui:"Artisan menuisier",heure:"Vendredi 7 h 30",prio:1,pb:"Ce matin, une radio et un chargeur de visseuse ont grillé ; certaines lampes brillent très fort, d'autres très faiblement.",contrainte:"Production arrêtée, une commande à livrer."},
  etapes:[
   {q:"Des lampes trop fortes et d'autres trop faibles en triphasé avec neutre : tu penses à…",o:[["Une coupure du neutre (rupture de neutre)",true,"Sans neutre, les circuits monophasés se retrouvent en série entre deux phases : certains reçoivent bien plus de 230 V."],["Une phase coupée",false,"Une phase coupée éteindrait les appareils de cette phase, sans surtension."],["Un différentiel défectueux",false,"Un différentiel coupe ou ne coupe pas ; il ne modifie pas les tensions."]]},
   {q:"Tout de suite, pour protéger le matériel :",o:[["Couper l'alimentation générale de l'atelier",true,"Tu coupes au général et tu préviens : on ne remet rien en route avant réparation."],["Débrancher seulement la radio",false,"Tous les appareils monophasés sont en danger."],["Observer pendant une heure",false,"Chaque minute sous tension peut griller d'autres appareils."]]},
   {info:"Mesures (habilitation BR, EPI). En aval du disjoncteur général : L1-N 312 V, L2-N 148 V, L3-N 235 V, L1-L2 400 V. En amont du disjoncteur général : L1-N 231 V, L2-N 229 V, L3-N 232 V.",q:"Conclusion ?",o:[["Le neutre est interrompu entre l'amont et l'aval du disjoncteur général",true,"En amont tout est normal ; en aval, les tensions phase-neutre sont déséquilibrées : le neutre « flotte » à partir de là."],["Le réseau est en surtension",false,"En amont, les tensions sont normales : le réseau n'y est pour rien."],["La phase L2 est coupée",false,"L1-L2 = 400 V : L2 est bien présente."]]},
   {info:"Dans le tableau, la borne de neutre en sortie du disjoncteur général est noircie, le conducteur desserré.",q:"Que fais-tu ?",o:[["Je consigne, je recoupe le neutre abîmé, je le reconnecte et je serre au couple du fabricant",true,"La connexion est refaite. Tu contrôles le serrage de toutes les autres bornes du tableau."],["J'ajoute un deuxième neutre en parallèle",false,"On répare la connexion, on ne bricole pas un neutre en parallèle."],["J'appelle le distributeur",false,"La borne est dans l'installation privée, après le disjoncteur de branchement : c'est ton travail."]]},
   {q:"Avant de remettre l'atelier en service :",o:[["Je mesure les tensions phase-neutre et je vérifie tous les serrages",true,"L1-N 231 V, L2-N 229 V, L3-N 232 V. Tu conseilles de faire vérifier les appareils qui ont pu souffrir."],["Je remets en route et je pars",false,"Après un défaut comme celui-là, on contrôle tout."],["Je laisse le neutre débranché",false,"Sans neutre, les surtensions recommenceraient."]]}],
  fin:"Rupture de neutre par connexion desserrée en sortie du disjoncteur général. Conséquence : tensions phase-neutre déséquilibrées et surtensions sur les circuits monophasés. Réparation, serrage de toutes les bornes, contrôle des tensions.",
  retenir:"Neutre coupé en triphasé = surtensions dangereuses. Le neutre se serre avec autant de soin que les phases."},

 {id:"moteur-sens",t:"Le convoyeur tourne à l'envers",ic:"⚙️",niv:3,
  bon:{lieu:"Entrepôt — convoyeur neuf",qui:"Responsable logistique",heure:"Lundi 15 h",prio:2,pb:"Le moteur du convoyeur, raccordé ce matin, fait tourner le tapis dans le mauvais sens.",contrainte:"Mise en service prévue à 17 h."},
  etapes:[
   {q:"Pour inverser le sens d'un moteur asynchrone triphasé :",o:[["On permute deux phases",true,"L'ordre des phases s'inverse, donc le sens du champ tournant aussi."],["On inverse le neutre et la terre",false,"Le moteur triphasé n'utilise pas le neutre, et on ne touche jamais au rôle de la terre."],["On permute les trois phases en rond",false,"L1→L2→L3→L1 garde le même ordre : le sens ne change pas."]]},
   {q:"Où et comment ?",o:[["Après consignation du départ moteur, à l'arrivée sur la plaque à bornes",true,"Sectionneur cadenassé, VAT entre phases et entre phases et terre, puis L1 et L2 permutées."],["Sous tension, rapidement",false,"Jamais sous tension."],["Au tableau général, sur l'arrivée",false,"Tous les moteurs de l'entrepôt changeraient de sens !"]]},
   {info:"Plaque signalétique : 1,5 kW — 230 V Δ / 400 V Y — 5,9 / 3,4 A. Réseau : 400 V entre phases.",q:"Le couplage doit être…",o:[["En étoile",true,"Sur 400 V, ce moteur se couple en étoile : barrettes entre W2, U2 et V2. C'est bien le cas."],["En triangle",false,"En triangle sur 400 V, chaque enroulement recevrait 400 V au lieu de 230 V : il brûlerait."],["Peu importe",false,"Une erreur de couplage détruit le moteur."]]},
   {q:"Le relais thermique doit être réglé sur…",o:[["3,4 A (intensité nominale en 400 V)",true,"On règle sur l'In de la plaque, pour la tension utilisée."],["6,8 A (le double)",false,"Trop haut : le moteur ne serait plus protégé contre la surcharge."],["5,9 A",false,"5,9 A est l'intensité en couplage triangle sur 230 V : ce n'est pas notre cas."]]},
   {q:"Essai :",o:[["Prévenir les personnes, essai bref, puis mesure de l'intensité à la pince sur chaque phase",true,"Le tapis tourne dans le bon sens. 2,9 A sur les trois phases, équilibrées et sous l'intensité nominale."],["Lancer directement la production",false,"Un essai et une mesure d'intensité d'abord."],["Attendre que le thermique déclenche pour voir s'il marche",false,"On ne provoque pas de surcharge pour tester."]]}],
  fin:"Sens de rotation inversé à la mise en service. Consignation, permutation de deux phases, contrôle du couplage étoile, réglage du thermique sur 3,4 A, essai et mesure des intensités.",
  retenir:"Sens : 2 phases. Couplage : selon la plaque et le réseau. Thermique : In de la plaque."},

 {id:"rj45",t:"Pas d'internet dans la chambre",ic:"🌐",niv:3,
  bon:{lieu:"Maison neuve — chambre 1",qui:"Client en télétravail",heure:"Mardi 9 h",prio:2,pb:"La prise RJ45 de la chambre ne donne pas internet. Celle du séjour fonctionne.",contrainte:"Le client a une visioconférence à 11 h."},
  etapes:[
   {q:"Où arrivent les câbles des prises RJ45 ?",o:[["Au tableau de communication, dans la GTL",true,"Chaque prise arrive sur un port du panneau de brassage, relié au switch ou à la box."],["Au tableau électrique, sur un disjoncteur",false,"Les RJ45 sont des courants faibles, sans disjoncteur."],["Directement à la box, sans tableau",false,"En neuf, tout est centralisé au tableau de communication."]]},
   {q:"Le port « Chambre 1 » n'est relié à rien. Tu poses un cordon vers le switch : toujours rien. Prochain test ?",o:[["Tester le lien entre le panneau et la prise avec un testeur RJ45",true,"Le testeur affiche des paires dans le désordre côté prise de la chambre."],["Changer la box",false,"La box fonctionne pour le séjour."],["Redémarrer l'ordinateur et attendre",false,"Le testeur de câble donne une réponse sûre."]]},
   {q:"Les deux extrémités doivent être câblées…",o:[["Selon le même code (T568A ou T568B) des deux côtés",true,"Côté panneau : T568B. Côté prise : un mélange. Tu recâbles la prise en T568B."],["N'importe comment si les 8 fils sont branchés",false,"Chaque paire doit arriver aux mêmes contacts des deux côtés."],["En T568A d'un côté et T568B de l'autre",false,"Cela fait un câble croisé, ce qu'on ne veut pas dans une installation fixe."]]},
   {q:"En recâblant, une bonne pratique :",o:[["Détorsader les paires le moins possible",true,"Le testeur affiche ensuite les 8 fils OK, et le client a sa visio."],["Dénuder 10 cm pour être à l'aise",false,"Détorsader beaucoup dégrade le débit."],["Passer le câble dans la gaine du 230 V",false,"Courants faibles et forts sont séparés."]]}],
  fin:"Port non brassé au tableau de communication et prise RJ45 mal câblée (paires inversées). Brassage, recâblage en T568B, test des 8 conducteurs.",
  retenir:"RJ45 : même code aux deux bouts, paires détorsadées au minimum, test systématique."},

 {id:"borne-ve",t:"La borne de recharge se met en défaut",ic:"🚗",niv:3,
  bon:{lieu:"Maison — garage, wallbox 7,4 kW posée il y a un mois",qui:"Mme Garcia",heure:"Lundi 8 h",prio:2,pb:"La recharge s'arrête au bout de quelques minutes et la borne affiche un défaut. Le disjoncteur et le différentiel de la borne restent enclenchés.",contrainte:"La cliente a besoin de sa voiture demain."},
  etapes:[
   {q:"Avant de démonter quoi que ce soit, tu…",o:[["Lis le code défaut dans la notice ou l'application de la borne",true,"Code « sous-tension » : la borne détecte une tension trop faible pendant la recharge."],["Remplaces la borne",false,"Changer pour voir coûte cher et ne trouve pas la cause."],["Augmentes le calibre du disjoncteur",false,"Rien n'a déclenché : ce n'est pas un problème de protection."]]},
   {q:"Tension trop faible pendant la recharge seulement. Hypothèse ?",o:[["Une chute de tension trop forte dans le câble (trop long ou trop fin), ou une connexion qui chauffe",true,"À 32 A, la moindre résistance en trop fait chuter la tension et chauffer."],["Une fuite à la terre",false,"Le différentiel serait déclenché."],["Un court-circuit",false,"Le disjoncteur aurait déclenché instantanément."]]},
   {info:"Le câble mesure 35 m en 6 mm². Pendant la recharge (32 A) : 228 V au tableau, 211 V à la borne.",q:"Qu'en déduis-tu ?",o:[["17 V de chute, c'est plus que ce que donne le calcul : il y a une résistance en trop quelque part",true,"Calcul : ΔU = 2 × 0,0225 × 35 × 32 ÷ 6 ≈ 8,4 V. On en mesure 17 : une connexion est en cause."],["C'est normal pour 35 m",false,"Le calcul donne environ 8,4 V : la mesure est deux fois plus forte."],["Le réseau est trop faible",false,"Au tableau, on a 228 V : le réseau est correct."]]},
   {q:"Où chercher ?",o:[["Consigner, puis contrôler les connexions (bornes du disjoncteur, boîte intermédiaire, bornier de la borne) : traces de chauffe, serrage",true,"Dans la boîte de dérivation du garage, une borne à vis du neutre est desserrée et brunie."],["Changer tout le câble",false,"Peut-être pas nécessaire : on cherche d'abord la connexion fautive."],["Rien, la voiture se rechargera moins vite",false,"Une connexion qui chauffe à 32 A pendant des heures, c'est un risque d'incendie."]]},
   {q:"Réparation et contrôle :",o:[["Remplacer la connexion abîmée, serrer au couple, puis mesurer la tension à la borne pendant une recharge",true,"Pendant la recharge : 220 V à la borne, chute conforme au calcul. La borne charge sans défaut."],["Mettre du ruban isolant sur la borne brunie",false,"Une connexion qui a chauffé se remplace."],["Réduire la puissance de charge et partir",false,"On a trouvé la cause : on la répare."]]}],
  fin:"Connexion de neutre desserrée dans une boîte intermédiaire : résistance supplémentaire, chute de tension anormale à 32 A, échauffement et défaut de sous-tension de la borne. Remplacement de la connexion, serrage, contrôle de la tension en charge.",
  retenir:"À fort courant permanent, une connexion mal serrée se voit à la chute de tension… avant de se voir à l'incendie."}
];
