/* Électricien Pro — contenu (titre pro Électricien d'équipement du bâtiment) */
const C={
 id:'electricien',app:'Électricien Pro',icon:'⚡',
 sousTitre:'Les modules du titre professionnel, en fiches courtes.',
 pub:{actif:true,toutesLes:3},
 modules:[
  {id:'bases',i:'🔌',t:'Les bases de l\'électricité',d:'Tension, courant, résistance, puissance',
   s:[{h:'Les 4 grandeurs',l:['<b>Tension (U)</b> en volts (V) : la « pression » qui pousse le courant.','<b>Intensité (I)</b> en ampères (A) : la quantité de courant qui circule.','<b>Résistance (R)</b> en ohms (Ω) : ce qui freine le courant.','<b>Puissance (P)</b> en watts (W) : l\'énergie consommée par seconde.']},
      {h:'Les 2 formules à connaître',l:['<b>Loi d\'Ohm : U = R × I</b>','<b>Puissance : P = U × I</b>','Exemple : un radiateur de 2 300 W en 230 V consomme I = 2300 ÷ 230 = <b>10 A</b>.']},
      {h:'Le réseau en France',l:['Monophasé : <b>230 V – 50 Hz</b> (logements).','Triphasé : <b>400 V</b> entre phases (gros équipements, ateliers).']}],
   k:['Tension','Intensité','Résistance','Puissance','Loi d\'Ohm']},
  {id:'secu',i:'🦺',t:'Sécurité & habilitation',d:'NF C 18-510, consignation, domaines de tension',
   s:[{h:'Les domaines de tension (alternatif)',l:['<b>TBT</b> : jusqu\'à 50 V.','<b>BT</b> : de 50 V à 1 000 V.','<b>HTA / HTB</b> : au-delà de 1 000 V.']},
      {h:'L\'habilitation électrique',l:['Obligatoire pour travailler sur ou près d\'installations électriques (norme <b>NF C 18-510</b>).','<b>B0</b> : non-électricien, travaux non électriques en zone à risque.','<b>BR</b> : interventions générales en basse tension (dépannage, raccordement).','<b>BC</b> : réaliser une consignation.','<b>B1 / B2</b> : exécutant / chargé de travaux électriques.']},
      {h:'La consignation',l:['1. <b>Séparer</b> l\'installation de sa source.','2. <b>Condamner</b> l\'organe de séparation (cadenas).','3. <b>Identifier</b> l\'ouvrage sur lequel on travaille.','4. <b>Vérifier l\'absence de tension</b> (VAT).','5. <b>Mettre à la terre et en court-circuit</b> si nécessaire.']}],
   k:['Habilitation','Consignation','VAT','EPI']},
  {id:'protec',i:'🛡️',t:'Protections & tableau',d:'Disjoncteurs, différentiels, NF C 15-100',
   s:[{h:'Qui protège quoi ?',l:['<b>Disjoncteur divisionnaire</b> : protège les <b>câbles</b> contre les surcharges et les courts-circuits.','<b>Interrupteur différentiel 30 mA</b> : protège les <b>personnes</b> contre les fuites de courant.','<b>Disjoncteur de branchement</b> : à l\'entrée du logement, coupe tout.']},
      {h:'Sections et calibres (NF C 15-100)',l:['Éclairage : <b>1,5 mm²</b> → disjoncteur <b>16 A</b>.','Prises (max 12) : <b>2,5 mm²</b> → <b>20 A</b>.','Lave-linge, four, chauffe-eau : circuit spécialisé <b>2,5 mm²</b> → <b>20 A</b>.','Plaque de cuisson : <b>6 mm²</b> → <b>32 A</b>.']},
      {h:'Les couleurs des fils',l:['<b>Vert/jaune</b> : terre (PE) — réservé, jamais autre chose.','<b>Bleu</b> : neutre.','<b>Phase</b> : rouge, marron, noir…']}],
   k:['Disjoncteur','Différentiel','Terre','Neutre','Phase','Court-circuit']},
  {id:'schemas',i:'💡',t:'Schémas & montages',d:'Simple allumage, va-et-vient, télérupteur',
   s:[{h:'Les montages d\'éclairage',l:['<b>Simple allumage</b> : 1 interrupteur commande 1 point lumineux.','<b>Va-et-vient</b> : 2 interrupteurs commandent le même point (couloir, escalier).','<b>Télérupteur</b> : 3 boutons poussoirs ou plus commandent le même point.','<b>Minuterie</b> : la lumière s\'éteint seule après un temps réglé.']},
      {h:'La règle d\'or',l:['L\'interrupteur coupe toujours la <b>phase</b>, jamais le neutre.']}],
   k:['Va-et-vient','Télérupteur','Phase']},
  {id:'mesure',i:'📟',t:'Mesures & contrôle',d:'Multimètre, VAT, pince ampèremétrique',
   s:[{h:'Bien brancher ses appareils',l:['<b>Voltmètre</b> : en <b>parallèle</b> (aux bornes).','<b>Ampèremètre</b> : en <b>série</b> (dans le circuit).','<b>Pince ampèremétrique</b> : autour d\'<b>un seul</b> conducteur.']},
      {h:'Le VAT',l:['Vérificateur d\'Absence de Tension : on le <b>teste avant et après</b> la mesure pour être sûr qu\'il fonctionne.','Un multimètre <b>ne remplace pas</b> un VAT.']}],
   k:['VAT','Multimètre']}
 ],
 lexique:[
  ['Tension','Différence de potentiel entre deux points, en volts (V). Symbole U.'],
  ['Intensité','Quantité de courant qui circule, en ampères (A). Symbole I.'],
  ['Résistance','Opposition au passage du courant, en ohms (Ω). Symbole R.'],
  ['Puissance','Énergie consommée par seconde, en watts (W). P = U × I.'],
  ['Loi d\'Ohm','U = R × I : la tension égale la résistance multipliée par l\'intensité.'],
  ['Phase','Conducteur sous tension (230 V par rapport au neutre). Rouge, marron ou noir.'],
  ['Neutre','Conducteur de retour du courant. Toujours bleu.'],
  ['Terre','Conducteur de protection (PE) qui évacue les fuites vers le sol. Toujours vert/jaune.'],
  ['Disjoncteur','Appareil qui coupe automatiquement un circuit en cas de surcharge ou de court-circuit.'],
  ['Différentiel','Appareil qui coupe dès qu\'il détecte une fuite de courant (30 mA pour protéger les personnes).'],
  ['Court-circuit','Contact direct entre phase et neutre : courant énorme, risque d\'incendie.'],
  ['Surcharge','Trop d\'appareils sur un circuit : le courant dépasse ce que le câble supporte.'],
  ['Habilitation','Autorisation donnée par l\'employeur pour travailler sur ou près d\'installations électriques.'],
  ['Consignation','Ensemble des étapes pour mettre une installation hors tension en toute sécurité.'],
  ['VAT','Vérificateur d\'Absence de Tension : appareil obligatoire avant toute intervention.'],
  ['EPI','Équipements de Protection Individuelle : gants isolants, écran facial, chaussures…'],
  ['Va-et-vient','Montage où 2 interrupteurs commandent le même point lumineux.'],
  ['Télérupteur','Relais commandé par plusieurs boutons poussoirs pour un même éclairage.'],
  ['Multimètre','Appareil de mesure : tension, intensité, résistance, continuité.'],
  ['NF C 15-100','Norme qui fixe les règles des installations électriques basse tension dans les logements.'],
  ['NF C 18-510','Norme qui encadre la prévention du risque électrique et l\'habilitation.'],
  ['TGBT','Tableau Général Basse Tension : tableau principal d\'un bâtiment.']
 ],
 quiz:[
  ['bases','Quelle est l\'unité de la tension ?',['Le volt (V)','L\'ampère (A)','Le watt (W)','L\'ohm (Ω)'],0,'La tension se mesure en volts.'],
  ['bases','Un radiateur de 2 300 W en 230 V consomme…',['10 A','23 A','5 A','100 A'],0,'I = P ÷ U = 2300 ÷ 230 = 10 A.'],
  ['bases','La loi d\'Ohm s\'écrit…',['U = R × I','P = R × I','I = U × R','R = U × I'],0,'U = R × I.'],
  ['bases','La tension du réseau domestique en France est…',['230 V','110 V','400 V','12 V'],0,'230 V monophasé, 50 Hz.'],
  ['bases','En triphasé, la tension entre deux phases est…',['400 V','230 V','690 V','110 V'],0,'400 V entre phases, 230 V entre phase et neutre.'],
  ['secu','Quelle norme encadre l\'habilitation électrique ?',['NF C 18-510','NF C 15-100','ISO 9001','NF EN 60204'],0,'La NF C 18-510 encadre la prévention du risque électrique.'],
  ['secu','Quelle habilitation pour un dépannage en basse tension ?',['BR','B0','H0','BC'],0,'BR = interventions générales en BT.'],
  ['secu','Après avoir séparé et condamné, on…',['Identifie l\'ouvrage','Coupe le neutre','Retire ses gants','Remet sous tension'],0,'Ordre : séparer, condamner, identifier, VAT, MALT-CC.'],
  ['secu','Le domaine BT en alternatif va de…',['50 V à 1 000 V','0 à 50 V','1 000 à 5 000 V','230 à 400 V'],0,'Basse tension : 50 V à 1 000 V en alternatif.'],
  ['secu','Que veut dire EPI ?',['Équipement de Protection Individuelle','Élément de Protection Intérieure','Essai de Prise Isolée','Équipement Pour Installation'],0,'Gants isolants, écran facial, etc.'],
  ['protec','Qui protège les personnes contre les fuites de courant ?',['Le différentiel 30 mA','Le disjoncteur divisionnaire','Le fusible','Le télérupteur'],0,'Le différentiel détecte la fuite et coupe.'],
  ['protec','Le disjoncteur divisionnaire protège surtout…',['Les câbles','Les personnes','Le compteur','La prise de terre'],0,'Il protège les câbles des surcharges et courts-circuits.'],
  ['protec','Section et calibre pour un circuit d\'éclairage ?',['1,5 mm² / 16 A','2,5 mm² / 32 A','6 mm² / 32 A','1 mm² / 10 A'],0,'Éclairage : 1,5 mm² protégé en 16 A.'],
  ['protec','Section pour une plaque de cuisson ?',['6 mm²','1,5 mm²','2,5 mm²','4 mm²'],0,'Plaque de cuisson : 6 mm² en 32 A.'],
  ['protec','Quelle couleur pour le neutre ?',['Bleu','Vert/jaune','Rouge','Noir'],0,'Le neutre est toujours bleu.'],
  ['protec','Le fil vert/jaune est…',['La terre','Le neutre','Une phase','Au choix'],0,'Vert/jaune = terre, uniquement.'],
  ['schemas','2 interrupteurs pour une même lampe, c\'est un…',['Va-et-vient','Simple allumage','Double allumage','Télérupteur'],0,'Va-et-vient : couloir, escalier.'],
  ['schemas','Pour 4 points de commande d\'un même éclairage on utilise…',['Un télérupteur','Un va-et-vient','Un simple allumage','Un différentiel'],0,'À partir de 3 points : télérupteur.'],
  ['schemas','L\'interrupteur doit couper…',['La phase','Le neutre','La terre','Les deux'],0,'On coupe toujours la phase.'],
  ['mesure','Un voltmètre se branche…',['En parallèle','En série','Autour du câble','Sur la terre'],0,'Le voltmètre se branche aux bornes, en parallèle.'],
  ['mesure','Un ampèremètre se branche…',['En série','En parallèle','Sur le neutre seul','Hors tension'],0,'L\'ampèremètre est dans le circuit, en série.'],
  ['mesure','La pince ampèremétrique se place autour…',['D\'un seul conducteur','De tout le câble','Du disjoncteur','De la prise'],0,'Autour du câble entier, les courants s\'annulent : la pince affiche 0.'],
  ['mesure','Avant et après la VAT, on doit…',['Tester le VAT','Couper le différentiel','Mesurer la terre','Changer les piles'],0,'On vérifie que le VAT fonctionne avant et après.']
 ],
 vf:[
  ['Le fil vert/jaune peut servir de phase si on manque de fil.',false,'Jamais : vert/jaune = terre uniquement.'],
  ['Un différentiel 30 mA protège les personnes.',true,'C\'est son rôle principal.'],
  ['L\'interrupteur coupe le neutre.',false,'Il coupe la phase.'],
  ['P = U × I.',true,'Puissance = tension × intensité.'],
  ['Un multimètre peut remplacer un VAT.',false,'Le VAT est obligatoire pour la vérification d\'absence de tension.'],
  ['Le neutre est bleu.',true,'Toujours bleu.'],
  ['Un ampèremètre se branche en parallèle.',false,'En série.'],
  ['La plaque de cuisson se câble en 6 mm².',true,'6 mm² protégé en 32 A.'],
  ['L\'habilitation B0 permet de faire du dépannage électrique.',false,'B0 = non-électricien. Le dépannage, c\'est BR.'],
  ['En France, la fréquence du réseau est de 50 Hz.',true,'230 V – 50 Hz.'],
  ['Le disjoncteur protège les câbles contre les surcharges.',true,'Surcharges et courts-circuits.'],
  ['La TBT va jusqu\'à 50 V en alternatif.',true,'Très Basse Tension : ≤ 50 V AC.'],
  ['Un va-et-vient utilise 3 interrupteurs.',false,'2 interrupteurs. Au-delà : télérupteur.'],
  ['Il faut tester le VAT avant et après la mesure.',true,'Pour être sûr qu\'il marche.']
 ],
 ordre:[
  {t:'La consignation électrique',s:['Séparer','Condamner','Identifier','Vérifier l\'absence de tension','Mettre à la terre et en court-circuit']},
  {t:'Remplacer une prise de courant',s:['Couper le disjoncteur du circuit','Vérifier l\'absence de tension','Démonter l\'ancienne prise','Raccorder phase, neutre et terre','Fixer la nouvelle prise','Remettre sous tension et tester']}
 ]
};
