/* Maths 3e – Brevet — contenu (programme de mathématiques du cycle 4, classe de 3e) */
const C={
 id:'maths3',app:'Maths 3e Brevet',icon:'🎯',
 sousTitre:'Tout le programme de 3e pour réussir le brevet, en fiches courtes.',
 theme:{pri:'#ff7eb6',pri2:'#c9407f',acc:'#5ad1ff'},
 pub:{actif:false,toutesLes:3},   // public mineur : voir docs/PUBLICITE.md avant d'activer
 examen:{titre:'Brevet blanc express',questions:20,seuil:12,minutes:25},
 calcul:[
  {op:'×',a:[6,15],b:[6,15]},
  {op:'÷',a:[6,15],b:[3,12]},
  {op:'+',a:[120,480],b:[45,390]},
  {op:'−',a:[200,600],b:[35,190]}
 ],
 modules:[
  {id:'nombres',i:'🔢',t:'Nombres & arithmétique',d:'Puissances, nombres premiers, fractions',
   s:[{h:'Les puissances',l:['a<sup>n</sup> = a × a × … × a (n fois). 2<sup>5</sup> = <b>32</b>.','10<sup>3</sup> = 1 000 ; 10<sup>−2</sup> = 0,01.','<b>Notation scientifique</b> : a × 10<sup>n</sup> avec 1 ≤ a < 10. Ex. : 45 000 = <b>4,5 × 10<sup>4</sup></b>.','Règles : a<sup>m</sup> × a<sup>n</sup> = a<sup>m+n</sup>.']},
      {h:'Nombres premiers',l:['Un <b>nombre premier</b> a exactement <b>2 diviseurs</b> : 1 et lui-même. 2, 3, 5, 7, 11, 13…','1 n\'est <b>pas</b> premier.','<b>Décomposer</b> en produit de facteurs premiers : 60 = 2² × 3 × 5.','Ça sert à <b>simplifier</b> une fraction : 60/84 = (2²×3×5)/(2²×3×7) = <b>5/7</b>.']},
      {h:'Fractions',l:['Additionner : même <b>dénominateur</b> d\'abord. 1/3 + 1/6 = 2/6 + 1/6 = <b>1/2</b>.','Multiplier : numérateurs ensemble, dénominateurs ensemble.','Diviser par une fraction = multiplier par son <b>inverse</b>.']}],
   k:['Puissance','Notation scientifique','Nombre premier','Inverse']},
  {id:'litteral',i:'✏️',t:'Calcul littéral & équations',d:'Développer, factoriser, résoudre',
   s:[{h:'Développer et factoriser',l:['<b>Développer</b> : transformer un produit en somme. k(a + b) = ka + kb.','Double distributivité : (a + b)(c + d) = ac + ad + bc + bd.','<b>Factoriser</b> : l\'inverse, transformer une somme en produit. 3x + 6 = 3(x + 2).']},
      {h:'L\'identité remarquable du brevet',l:['<b>(a + b)(a − b) = a² − b²</b>.','Exemple : x² − 9 = (x + 3)(x − 3).']},
      {h:'Résoudre une équation',l:['On isole x en faisant <b>la même opération des deux côtés</b>.','3x + 5 = 20 → 3x = 15 → <b>x = 5</b>.','<b>Équation produit nul</b> : si A × B = 0, alors A = 0 <b>ou</b> B = 0.','(x − 2)(x + 4) = 0 → x = 2 ou x = −4.']}],
   k:['Développer','Factoriser','Équation','Produit nul']},
  {id:'geometrie',i:'📐',t:'Pythagore, Thalès, trigonométrie',d:'Les 3 outils des triangles',
   s:[{h:'Pythagore',l:['Dans un triangle <b>rectangle</b> : <b>hypoténuse² = somme des carrés des deux autres côtés</b>.','Côtés 3 et 4 → hypoténuse² = 9 + 16 = 25 → hypoténuse = <b>5</b>.','La <b>réciproque</b> permet de prouver qu\'un triangle est rectangle.']},
      {h:'Thalès',l:['Deux droites <b>parallèles</b> coupent deux sécantes : les longueurs sont <b>proportionnelles</b>.','AM/AB = AN/AC = MN/BC.','La <b>réciproque</b> prouve que deux droites sont parallèles.']},
      {h:'Trigonométrie',l:['Seulement dans un triangle <b>rectangle</b>.','<b>SOH CAH TOA</b> :','sin = <b>opposé ÷ hypoténuse</b>','cos = <b>adjacent ÷ hypoténuse</b>','tan = <b>opposé ÷ adjacent</b>']}],
   k:['Hypoténuse','Pythagore','Thalès','Cosinus','Réciproque']},
  {id:'fonctions',i:'📈',t:'Les fonctions',d:'Image, antécédent, linéaire, affine',
   s:[{h:'Vocabulaire',l:['f(x) = 2x + 1. Pour x = 3, f(3) = 7.','7 est l\'<b>image</b> de 3. 3 est un <b>antécédent</b> de 7.','On lit l\'image sur l\'axe <b>vertical</b> (ordonnées).']},
      {h:'Fonction linéaire',l:['<b>f(x) = ax</b>. Sa courbe est une <b>droite qui passe par l\'origine</b>.','Elle représente une situation de <b>proportionnalité</b>.']},
      {h:'Fonction affine',l:['<b>f(x) = ax + b</b>. Sa courbe est une <b>droite</b>.','<b>a</b> = coefficient directeur (la pente) · <b>b</b> = ordonnée à l\'origine.','Si a > 0, la droite monte ; si a < 0, elle descend.']}],
   k:['Image','Antécédent','Fonction affine','Fonction linéaire']},
  {id:'stats',i:'🎲',t:'Statistiques & probabilités',d:'Moyenne, médiane, étendue, probabilité',
   s:[{h:'Statistiques',l:['<b>Moyenne</b> = somme des valeurs ÷ nombre de valeurs.','<b>Médiane</b> : valeur du milieu quand la série est <b>rangée</b> dans l\'ordre.','<b>Étendue</b> = plus grande valeur − plus petite valeur.','Série 4 ; 7 ; 9 ; 12 ; 18 → moyenne 10, médiane 9, étendue 14.']},
      {h:'Probabilités',l:['Probabilité = <b>nombre de cas favorables ÷ nombre de cas possibles</b>.','Elle est toujours entre <b>0</b> (impossible) et <b>1</b> (certain).','Dé à 6 faces : P(obtenir un 6) = <b>1/6</b>.','P(événement contraire) = 1 − P(événement).']}],
   k:['Moyenne','Médiane','Étendue','Probabilité']}
 ],
 lexique:[
  ['Puissance','a^n = a multiplié n fois par lui-même. 3² = 9.'],
  ['Notation scientifique','Écriture a × 10^n avec 1 ≤ a < 10. Ex. : 0,005 = 5 × 10^−3.'],
  ['Nombre premier','Nombre entier qui a exactement deux diviseurs : 1 et lui-même.'],
  ['Inverse','L\'inverse de a/b est b/a. Un nombre multiplié par son inverse donne 1.'],
  ['Développer','Transformer un produit en somme : 2(x + 3) = 2x + 6.'],
  ['Factoriser','Transformer une somme en produit : 2x + 6 = 2(x + 3).'],
  ['Équation','Égalité avec une inconnue. La résoudre, c\'est trouver la valeur de l\'inconnue.'],
  ['Produit nul','Un produit est nul si et seulement si un de ses facteurs est nul.'],
  ['Hypoténuse','Le plus grand côté d\'un triangle rectangle, face à l\'angle droit.'],
  ['Pythagore','Dans un triangle rectangle : hypoténuse² = somme des carrés des deux autres côtés.'],
  ['Thalès','Avec deux droites parallèles, les longueurs des deux triangles sont proportionnelles.'],
  ['Cosinus','Dans un triangle rectangle : côté adjacent ÷ hypoténuse.'],
  ['Réciproque','Théorème « à l\'envers » : sert à prouver qu\'un triangle est rectangle ou que des droites sont parallèles.'],
  ['Image','Le résultat f(x) d\'une fonction pour une valeur x.'],
  ['Antécédent','Valeur de x qui a une image donnée.'],
  ['Fonction affine','Fonction f(x) = ax + b, représentée par une droite.'],
  ['Fonction linéaire','Fonction f(x) = ax, droite qui passe par l\'origine. Traduit la proportionnalité.'],
  ['Moyenne','Somme des valeurs divisée par le nombre de valeurs.'],
  ['Médiane','Valeur qui partage la série rangée en deux moitiés de même effectif.'],
  ['Étendue','Écart entre la plus grande et la plus petite valeur.'],
  ['Probabilité','Nombre entre 0 et 1 qui mesure la chance qu\'un événement se produise.']
 ],
 quiz:[
  ['nombres','2⁵ = ?',['32','10','25','16'],0,'2 × 2 × 2 × 2 × 2 = 32.'],
  ['nombres','45 000 en notation scientifique s\'écrit…',['4,5 × 10⁴','45 × 10³','4,5 × 10³','0,45 × 10⁵'],0,'1 ≤ 4,5 < 10 et on décale la virgule de 4 rangs.'],
  ['nombres','10⁻² = ?',['0,01','−100','0,1','−20'],0,'Une puissance négative de 10 donne un nombre décimal.'],
  ['nombres','Lequel est un nombre premier ?',['13','21','1','27'],0,'13 n\'a que 1 et 13 comme diviseurs.'],
  ['nombres','La décomposition de 60 en facteurs premiers est…',['2² × 3 × 5','6 × 10','2 × 30','4 × 15'],0,'60 = 2 × 2 × 3 × 5.'],
  ['nombres','1/3 + 1/6 = ?',['1/2','2/9','1/9','2/6'],0,'2/6 + 1/6 = 3/6 = 1/2.'],
  ['nombres','2/3 ÷ 4/5 = ?',['5/6','8/15','6/5','10/12'],0,'2/3 × 5/4 = 10/12 = 5/6.'],
  ['nombres','3² × 3³ = ?',['3⁵','3⁶','9⁵','6⁵'],0,'On additionne les exposants.'],
  ['litteral','Développe 3(x + 4).',['3x + 12','3x + 4','x + 12','7x'],0,'3 × x + 3 × 4.'],
  ['litteral','Factorise 5x + 10.',['5(x + 2)','5(x + 10)','x(5 + 10)','10(x + 5)'],0,'5 est le facteur commun.'],
  ['litteral','(x + 2)(x + 3) = ?',['x² + 5x + 6','x² + 6','x² + 6x + 5','2x + 5'],0,'x² + 3x + 2x + 6.'],
  ['litteral','x² − 25 = ?',['(x + 5)(x − 5)','(x − 5)²','(x + 5)²','(x − 25)(x + 1)'],0,'a² − b² = (a + b)(a − b).'],
  ['litteral','Résous 3x + 5 = 20.',['x = 5','x = 15','x = 25/3','x = 8'],0,'3x = 15, donc x = 5.'],
  ['litteral','Résous 2x − 7 = x + 1.',['x = 8','x = 6','x = −8','x = 2'],0,'2x − x = 1 + 7.'],
  ['litteral','Les solutions de (x − 2)(x + 4) = 0 sont…',['2 et −4','−2 et 4','2 et 4','0'],0,'Produit nul : x − 2 = 0 ou x + 4 = 0.'],
  ['geometrie','Triangle rectangle de côtés 3 cm et 4 cm. L\'hypoténuse mesure…',['5 cm','7 cm','25 cm','12 cm'],0,'3² + 4² = 25 = 5².'],
  ['geometrie','Triangle rectangle : hypoténuse 10, un côté 6. L\'autre côté mesure…',['8','4','16','√136'],0,'10² − 6² = 64 = 8².'],
  ['geometrie','Le cosinus d\'un angle aigu, c\'est…',['Adjacent ÷ hypoténuse','Opposé ÷ hypoténuse','Opposé ÷ adjacent','Hypoténuse ÷ adjacent'],0,'CAH.'],
  ['geometrie','La tangente d\'un angle aigu, c\'est…',['Opposé ÷ adjacent','Adjacent ÷ opposé','Opposé ÷ hypoténuse','Adjacent ÷ hypoténuse'],0,'TOA.'],
  ['geometrie','Pour prouver que deux droites sont parallèles, on utilise…',['La réciproque de Thalès','Le théorème de Pythagore','Le cosinus','La moyenne'],0,'La réciproque de Thalès.'],
  ['geometrie','(MN) // (BC), AM = 3, AB = 6, BC = 10. MN = ?',['5','20','3','6'],0,'AM/AB = MN/BC → 3/6 = MN/10 → MN = 5.'],
  ['geometrie','La trigonométrie s\'utilise dans un triangle…',['Rectangle','Quelconque','Équilatéral seulement','Isocèle seulement'],0,'Seulement en triangle rectangle au collège.'],
  ['fonctions','f(x) = 2x + 1. L\'image de 3 est…',['7','5','1','6'],0,'2 × 3 + 1 = 7.'],
  ['fonctions','f(x) = 2x + 1. Un antécédent de 9 est…',['4','19','5','8'],0,'2x + 1 = 9 → x = 4.'],
  ['fonctions','f(x) = 4x est une fonction…',['Linéaire','Affine non linéaire','Constante','Carré'],0,'Forme ax, sans b.'],
  ['fonctions','Dans f(x) = −2x + 5, le coefficient directeur est…',['−2','5','2','−5'],0,'C\'est a dans ax + b.'],
  ['fonctions','La courbe d\'une fonction linéaire passe toujours par…',['L\'origine','Le point (1 ; 1)','Le point (0 ; 1)','Aucun point fixe'],0,'f(0) = 0.'],
  ['fonctions','f(x) = −3x + 2. La droite…',['Descend','Monte','Est horizontale','Est verticale'],0,'a < 0 : la droite descend.'],
  ['stats','Moyenne de 4 ; 7 ; 9 ; 12 ; 18 ?',['10','9','14','12'],0,'50 ÷ 5 = 10.'],
  ['stats','Médiane de 4 ; 7 ; 9 ; 12 ; 18 ?',['9','10','7','12'],0,'La valeur du milieu de la série rangée.'],
  ['stats','Étendue de 4 ; 7 ; 9 ; 12 ; 18 ?',['14','18','4','22'],0,'18 − 4 = 14.'],
  ['stats','Probabilité d\'obtenir un nombre pair avec un dé à 6 faces ?',['1/2','1/6','1/3','2/3'],0,'3 cas favorables (2, 4, 6) sur 6.'],
  ['stats','P(A) = 0,3. P(contraire de A) = ?',['0,7','0,3','1,3','−0,3'],0,'1 − 0,3 = 0,7.'],
  ['stats','Une probabilité peut valoir…',['0,8','1,5','−0,2','3'],0,'Toujours entre 0 et 1.']
 ],
 vf:[
  ['1 est un nombre premier.',false,'Il n\'a qu\'un seul diviseur.'],
  ['2³ = 6.',false,'2³ = 8.'],
  ['(a + b)(a − b) = a² − b².',true,'Identité remarquable.'],
  ['Factoriser, c\'est transformer une somme en produit.',true,'L\'inverse de développer.'],
  ['Pythagore marche dans tous les triangles.',false,'Seulement dans les triangles rectangles.'],
  ['L\'hypoténuse est le plus grand côté du triangle rectangle.',true,'Elle est face à l\'angle droit.'],
  ['sin = adjacent ÷ hypoténuse.',false,'C\'est le cosinus. sin = opposé ÷ hypoténuse.'],
  ['Une fonction linéaire est aussi une fonction affine.',true,'Avec b = 0.'],
  ['La médiane est toujours égale à la moyenne.',false,'Elles sont souvent différentes.'],
  ['Une probabilité est toujours entre 0 et 1.',true,'0 = impossible, 1 = certain.'],
  ['0,0042 = 4,2 × 10⁻³.',true,'On décale la virgule de 3 rangs vers la droite.'],
  ['Si A × B = 0, alors A = 0 ou B = 0.',true,'Équation produit nul.'],
  ['Diviser par 2/3 revient à multiplier par 3/2.',true,'On multiplie par l\'inverse.'],
  ['f(x) = 3x + 2 passe par l\'origine.',false,'f(0) = 2 : elle coupe l\'axe des ordonnées en 2.']
 ],
 ordre:[
  {t:'Rédiger un calcul avec Pythagore',s:['Le triangle ABC est rectangle en A','D\'après le théorème de Pythagore : BC² = AB² + AC²','BC² = 3² + 4²','BC² = 25','BC = √25 = 5 cm']},
  {t:'Résoudre 4x − 3 = 2x + 9',s:['4x − 2x = 9 + 3','2x = 12','x = 12 ÷ 2','x = 6','Vérifier : 4 × 6 − 3 = 21 et 2 × 6 + 9 = 21']},
  {t:'Calculer la médiane de 12 ; 5 ; 9 ; 3 ; 15',s:['Ranger la série : 3 ; 5 ; 9 ; 12 ; 15','Compter les valeurs : 5','Prendre celle du milieu : la 3e','La médiane est 9']}
 ]
};
