/* Maths 6e — contenu (programme de mathématiques du cycle 3, classe de 6e)
   Le moteur est le même que pour les métiers ; C.calcul ajoute le jeu « Calcul mental ». */
const C={
 id:'maths6',app:'Maths 6e',icon:'📐',
 sousTitre:'Le programme de 6e, chapitre par chapitre, en fiches courtes.',
 theme:{pri:'#5ad1ff',pri2:'#1a8fc4',acc:'#ffc83d'},
 pub:{actif:false,toutesLes:3},   // public mineur : voir docs/PUBLICITE.md avant d'activer
 calcul:[
  {op:'+',a:[12,99],b:[11,99]},
  {op:'−',a:[30,150],b:[11,60]},
  {op:'×',a:[2,10],b:[2,10]},
  {op:'×',a:[11,25],b:[2,5]},
  {op:'÷',a:[2,10],b:[2,10]}
 ],
 modules:[
  {id:'decimaux',i:'🔢',t:'Les nombres décimaux',d:'Écrire, comparer, ranger',
   s:[{h:'Partie entière et partie décimale',l:['Dans <b>12,35</b> : la partie entière est <b>12</b>, la partie décimale est <b>35</b> (centièmes).','Rang après la virgule : <b>dixièmes</b>, <b>centièmes</b>, <b>millièmes</b>.','12,35 = 12 + 3/10 + 5/100.']},
      {h:'Comparer deux décimaux',l:['On compare d\'abord les <b>parties entières</b>.','Si elles sont égales, on compare chiffre par chiffre après la virgule.','Astuce : on ajoute des zéros. 2,5 et 2,45 → <b>2,50 > 2,45</b>.']},
      {h:'Ranger',l:['<b>Ordre croissant</b> : du plus petit au plus grand.','<b>Ordre décroissant</b> : du plus grand au plus petit.']}],
   k:['Nombre décimal','Dixième','Centième','Ordre croissant']},
  {id:'operations',i:'➕',t:'Les quatre opérations',d:'Somme, différence, produit, quotient',
   s:[{h:'Le vocabulaire',l:['Le résultat d\'une addition est une <b>somme</b>.','Le résultat d\'une soustraction est une <b>différence</b>.','Le résultat d\'une multiplication est un <b>produit</b>.','Le résultat d\'une division est un <b>quotient</b>.']},
      {h:'Multiplier par 10, 100, 1 000',l:['× 10 : chaque chiffre prend une valeur <b>10 fois plus grande</b>.','3,7 × 10 = <b>37</b> ; 3,7 × 100 = <b>370</b>.','÷ 10 : 45 ÷ 10 = <b>4,5</b>.']},
      {h:'Multiples et diviseurs',l:['15 est un <b>multiple</b> de 3 car 15 = 3 × 5.','3 est un <b>diviseur</b> de 15.','Un nombre est divisible par 2 s\'il est pair, par 5 s\'il finit par 0 ou 5.']}],
   k:['Somme','Différence','Produit','Quotient','Multiple','Diviseur']},
  {id:'fractions',i:'🍕',t:'Les fractions',d:'Partager, lire, placer',
   s:[{h:'Lire une fraction',l:['Dans <b>3/4</b> : 3 est le <b>numérateur</b>, 4 est le <b>dénominateur</b>.','On partage l\'unité en 4 parts égales et on en prend 3.','3/4 se lit « trois quarts ».']},
      {h:'Fraction et quotient',l:['<b>a/b</b> est le nombre qui multiplié par b donne a.','3/4 = 3 ÷ 4 = <b>0,75</b>.','1/2 = 0,5 ; 1/4 = 0,25 ; 1/10 = 0,1.']},
      {h:'Prendre une fraction d\'une quantité',l:['3/4 de 20 = 20 ÷ 4 × 3 = <b>15</b>.']}],
   k:['Fraction','Numérateur','Dénominateur']},
  {id:'geometrie',i:'📏',t:'Droites, angles, cercles',d:'Parallèles, perpendiculaires, angles',
   s:[{h:'Les droites',l:['Deux droites <b>perpendiculaires</b> se coupent en formant un angle droit.','Deux droites <b>parallèles</b> ne se coupent jamais.','La <b>médiatrice</b> d\'un segment est perpendiculaire à ce segment en son milieu.']},
      {h:'Les angles',l:['<b>Angle aigu</b> : moins de 90°.','<b>Angle droit</b> : exactement 90°.','<b>Angle obtus</b> : entre 90° et 180°.','<b>Angle plat</b> : 180°. On mesure avec un <b>rapporteur</b>.']},
      {h:'Le cercle',l:['Le <b>rayon</b> relie le centre à un point du cercle.','Le <b>diamètre</b> = 2 × rayon.']}],
   k:['Perpendiculaires','Parallèles','Médiatrice','Angle droit','Angle aigu','Angle obtus','Rayon','Diamètre']},
  {id:'mesures',i:'📦',t:'Périmètres & aires',d:'Mesurer le tour et la surface',
   s:[{h:'Le périmètre',l:['Le <b>périmètre</b> est la longueur du tour d\'une figure.','Carré de côté c : <b>P = 4 × c</b>.','Rectangle : <b>P = 2 × (L + l)</b>.','Cercle : <b>P = 2 × π × r</b> (π ≈ 3,14).']},
      {h:'L\'aire',l:['L\'<b>aire</b> est la mesure de la surface, en cm², m²…','Carré : <b>A = c × c</b>.','Rectangle : <b>A = L × l</b>.','Triangle rectangle : <b>A = (base × hauteur) ÷ 2</b>.']},
      {h:'Proportionnalité',l:['Deux grandeurs sont <b>proportionnelles</b> si on passe de l\'une à l\'autre en multipliant toujours par le même nombre.','3 stylos coûtent 6 € → 6 stylos coûtent <b>12 €</b>.']}],
   k:['Périmètre','Aire','Proportionnalité']}
 ],
 lexique:[
  ['Nombre décimal','Nombre qui peut s\'écrire avec une virgule et un nombre fini de chiffres après : 3,25.'],
  ['Dixième','Une unité partagée en 10 parts égales : 1/10 = 0,1.'],
  ['Centième','Une unité partagée en 100 parts égales : 1/100 = 0,01.'],
  ['Ordre croissant','Du plus petit au plus grand.'],
  ['Somme','Résultat d\'une addition. La somme de 4 et 5 est 9.'],
  ['Différence','Résultat d\'une soustraction. La différence de 9 et 4 est 5.'],
  ['Produit','Résultat d\'une multiplication. Le produit de 4 par 5 est 20.'],
  ['Quotient','Résultat d\'une division. Le quotient de 20 par 4 est 5.'],
  ['Multiple','24 est un multiple de 6 car 24 = 6 × 4.'],
  ['Diviseur','6 est un diviseur de 24 car 24 ÷ 6 tombe juste.'],
  ['Fraction','Nombre écrit a/b : on partage en b parts égales et on en prend a.'],
  ['Numérateur','Nombre du haut d\'une fraction : le nombre de parts prises.'],
  ['Dénominateur','Nombre du bas d\'une fraction : en combien de parts on partage.'],
  ['Perpendiculaires','Deux droites qui se coupent en formant un angle droit.'],
  ['Parallèles','Deux droites qui ne se coupent jamais.'],
  ['Médiatrice','Droite perpendiculaire à un segment en son milieu.'],
  ['Angle droit','Angle de 90°, comme le coin d\'une feuille.'],
  ['Angle aigu','Angle plus petit qu\'un angle droit (moins de 90°).'],
  ['Angle obtus','Angle plus grand qu\'un angle droit et plus petit qu\'un angle plat.'],
  ['Rayon','Distance entre le centre du cercle et un point du cercle.'],
  ['Diamètre','Segment qui traverse le cercle en passant par le centre. Il vaut 2 rayons.'],
  ['Périmètre','Longueur du tour d\'une figure.'],
  ['Aire','Mesure de la surface d\'une figure, en unités d\'aire (cm², m²…).'],
  ['Proportionnalité','Deux grandeurs liées par un même coefficient multiplicateur.']
 ],
 quiz:[
  ['decimaux','Dans 45,78, le chiffre des dixièmes est…',['7','8','5','4'],0,'Le premier chiffre après la virgule est celui des dixièmes.'],
  ['decimaux','Quel nombre est le plus grand ?',['2,5','2,45','2,099','2,4'],0,'2,50 > 2,45 > 2,40 > 2,099.'],
  ['decimaux','3 + 7/100 s\'écrit…',['3,07','3,7','3,007','37'],0,'7 centièmes : deuxième chiffre après la virgule.'],
  ['decimaux','Entre 4,1 et 4,2, on peut placer…',['4,15','4,25','4,05','4,3'],0,'4,10 < 4,15 < 4,20.'],
  ['operations','Le résultat d\'une multiplication s\'appelle…',['Un produit','Une somme','Un quotient','Une différence'],0,'Multiplication → produit.'],
  ['operations','3,7 × 100 = ?',['370','37','3 700','0,037'],0,'Chaque chiffre prend une valeur 100 fois plus grande.'],
  ['operations','45 ÷ 10 = ?',['4,5','450','0,45','45,10'],0,'Diviser par 10 rend chaque chiffre 10 fois plus petit.'],
  ['operations','Lequel est un multiple de 7 ?',['42','27','45','71'],0,'42 = 7 × 6.'],
  ['operations','Un nombre divisible par 5 se termine par…',['0 ou 5','2 ou 4','5 uniquement','un chiffre pair'],0,'Critère de divisibilité par 5.'],
  ['fractions','Dans 3/8, le dénominateur est…',['8','3','11','5'],0,'Le dénominateur est en bas.'],
  ['fractions','1/4 = ?',['0,25','0,4','0,14','4'],0,'1 ÷ 4 = 0,25.'],
  ['fractions','3/4 de 20 = ?',['15','12','5','60'],0,'20 ÷ 4 = 5, puis 5 × 3 = 15.'],
  ['fractions','Quelle fraction vaut 0,5 ?',['1/2','1/5','5/1','2/5'],0,'1 ÷ 2 = 0,5.'],
  ['geometrie','Un angle de 120° est…',['Obtus','Aigu','Droit','Plat'],0,'Entre 90° et 180° : obtus.'],
  ['geometrie','Deux droites qui ne se coupent jamais sont…',['Parallèles','Perpendiculaires','Sécantes','Médiatrices'],0,'Parallèles.'],
  ['geometrie','Le rayon d\'un cercle de diamètre 10 cm est…',['5 cm','20 cm','10 cm','3,14 cm'],0,'Rayon = diamètre ÷ 2.'],
  ['geometrie','Pour mesurer un angle, on utilise…',['Un rapporteur','Un compas','Une règle seule','Une équerre'],0,'Le rapporteur mesure en degrés.'],
  ['mesures','Périmètre d\'un carré de côté 6 cm ?',['24 cm','36 cm','12 cm','36 cm²'],0,'P = 4 × 6 = 24 cm.'],
  ['mesures','Aire d\'un rectangle de 5 cm sur 3 cm ?',['15 cm²','16 cm','8 cm²','15 cm'],0,'A = 5 × 3 = 15 cm².'],
  ['mesures','Aire d\'un triangle rectangle de côtés 4 cm et 6 cm (angle droit entre eux) ?',['12 cm²','24 cm²','10 cm²','20 cm²'],0,'(4 × 6) ÷ 2 = 12 cm².'],
  ['mesures','2 kg de pommes coûtent 5 €. 6 kg coûtent…',['15 €','11 €','30 €','12 €'],0,'3 fois plus de pommes → 3 fois plus cher.'],
  ['mesures','L\'aire se mesure en…',['cm²','cm','degrés','litres'],0,'Une surface se mesure en unités carrées.']
 ],
 vf:[
  ['2,5 est plus grand que 2,45.',true,'2,50 > 2,45.'],
  ['Le produit de 6 et 4 est 10.',false,'Le produit est 24. 10 est leur somme.'],
  ['1/2 = 0,5.',true,'1 ÷ 2 = 0,5.'],
  ['Un angle droit mesure 100°.',false,'Il mesure 90°.'],
  ['Le diamètre est le double du rayon.',true,'D = 2 × r.'],
  ['Le périmètre se mesure en cm².',false,'En cm. L\'aire se mesure en cm².'],
  ['36 est un multiple de 9.',true,'36 = 9 × 4.'],
  ['0,7 = 7/100.',false,'0,7 = 7/10.'],
  ['Deux droites perpendiculaires forment un angle droit.',true,'C\'est leur définition.'],
  ['5,2 × 10 = 5,20.',false,'5,2 × 10 = 52.'],
  ['Dans 7/9, 7 est le numérateur.',true,'Le numérateur est en haut.'],
  ['Un angle de 45° est aigu.',true,'Moins de 90°.'],
  ['Le quotient de 30 par 5 est 6.',true,'30 ÷ 5 = 6.'],
  ['L\'aire d\'un carré de côté 3 cm est 12 cm².',false,'3 × 3 = 9 cm². 12 cm est son périmètre.']
 ],
 ordre:[
  {t:'Range dans l\'ordre croissant',s:['0,09','0,5','0,55','1,05','1,5','10,1']},
  {t:'Construire la médiatrice d\'un segment [AB] au compas',s:['Tracer le segment [AB]','Ouvrir le compas plus que la moitié de AB','Tracer un arc de centre A','Tracer un arc de centre B avec le même écartement','Relier les 2 points d\'intersection des arcs']},
  {t:'Calculer l\'aire d\'un rectangle',s:['Mesurer la longueur','Mesurer la largeur','Vérifier qu\'elles sont dans la même unité','Multiplier longueur × largeur','Écrire le résultat en unité d\'aire (cm²)']}
 ]
};
