/* Paie Pro — contenu (titre pro Gestionnaire de paie)
   ⚠️ CHIFFRES 2026 : SMIC, plafond de la Sécurité sociale et taux sont à mettre à jour chaque 1er janvier.
   À faire relire par un formateur paie avant publication. */
const C={
 id:'paie',app:'Paie Pro',icon:'💶',
 sousTitre:'Le titre pro Gestionnaire de paie, en fiches courtes. Chiffres 2026.',
 theme:{pri:'#7ee081',pri2:'#3fa646',acc:'#5ad1ff'},
 pub:{actif:true,toutesLes:3},
 examen:{titre:'Test de connaissances paie',questions:30,seuil:21,minutes:30},
 modules:[
  {id:'bulletin',i:'🧾',t:'Le bulletin de paie',d:'Du brut au net à payer',
   s:[{h:'Les grandes étapes',l:['<b>Salaire brut</b> = salaire de base + heures supplémentaires + primes + avantages − absences.','− <b>cotisations salariales</b> → <b>net avant impôt</b>.','− <b>prélèvement à la source</b> (impôt sur le revenu) → <b>net à payer</b>.','Le bulletin affiche aussi le <b>montant net social</b> (sert au calcul des aides sociales).']},
      {h:'Ordres de grandeur',l:['Cotisations <b>salariales</b> : environ <b>22 %</b> du brut pour un non-cadre.','Cotisations <b>patronales</b> : environ <b>40 à 45 %</b> du brut (avant réductions).','Donc net avant impôt ≈ <b>78 %</b> du brut. Exemple : 2 000 € brut → environ 1 560 € net.']},
      {h:'Obligations',l:['Le bulletin est remis à chaque paie, sur papier ou en version électronique (sauf refus du salarié).','L\'employeur conserve un double <b>5 ans</b>. Le salarié le garde <b>sans limite de durée</b>.']}],
   k:['Salaire brut','Net à payer','Montant net social','Prélèvement à la source']},
  {id:'temps',i:'⏱️',t:'Salaire & temps de travail',d:'SMIC, taux horaire, heures supplémentaires',
   s:[{h:'Les chiffres de base (2026)',l:['Durée légale : <b>35 h par semaine</b>, soit <b>151,67 h par mois</b>.','<b>SMIC horaire brut : 12,02 €</b>.','<b>SMIC mensuel brut : 1 823,03 €</b> (35 h).','Taux horaire = salaire mensuel ÷ 151,67.']},
      {h:'Les heures supplémentaires',l:['Ce sont les heures faites <b>au-delà de 35 h</b> par semaine.','Majoration légale (sans accord) : <b>+25 %</b> de la 36e à la 43e heure, <b>+50 %</b> à partir de la 44e.','Un accord d\'entreprise peut fixer un taux différent, <b>au minimum 10 %</b>.','Exemple : taux horaire 15 €, 4 h sup à 25 % → 4 × 15 × 1,25 = <b>75 €</b>.']},
      {h:'Hiérarchie des règles',l:['Code du travail → <b>convention collective</b> de branche → accord d\'entreprise → contrat de travail.','La convention collective fixe souvent les salaires minimums, les primes et les préavis : toujours la vérifier.']}],
   k:['SMIC','Heures supplémentaires','Convention collective','Taux horaire']},
  {id:'cotis',i:'🏛️',t:'Les cotisations',d:'Plafond, CSG/CRDS, retraite, chômage',
   s:[{h:'Le plafond de la Sécurité sociale',l:['<b>PMSS 2026 : 4 005 €</b> par mois (PASS : 48 060 € par an).','Certaines cotisations ne s\'appliquent que jusqu\'au plafond (<b>tranche A / T1</b>), d\'autres sur tout le salaire (<b>déplafonnées</b>).']},
      {h:'CSG et CRDS',l:['Assiette : <b>98,25 %</b> du brut (abattement de 1,75 % pour frais professionnels).','<b>CSG déductible : 6,8 %</b> · <b>CSG non déductible : 2,4 %</b> · <b>CRDS : 0,5 %</b>.','La CSG non déductible et la CRDS sont soumises à l\'impôt sur le revenu.']},
      {h:'Les principales cotisations',l:['<b>Maladie, vieillesse, allocations familiales, accidents du travail</b> : URSSAF.','<b>Retraite complémentaire</b> : Agirc-Arrco, sur tranches T1 et T2.','<b>Assurance chômage</b> : uniquement patronale (plus de part salariale depuis 2018).','<b>Mutuelle</b> : obligatoire, l\'employeur paie <b>au moins 50 %</b>.']}],
   k:['PMSS','CSG','CRDS','URSSAF','Agirc-Arrco']},
  {id:'absences',i:'🏖️',t:'Congés & absences',d:'Congés payés, maladie, retenues',
   s:[{h:'Les congés payés',l:['On acquiert <b>2,5 jours ouvrables par mois</b> travaillé, soit <b>30 jours ouvrables</b> (5 semaines) par an.','Période de référence habituelle : du <b>1er juin au 31 mai</b>.','Indemnité : on compare le <b>maintien de salaire</b> et la <b>règle du dixième</b> (1/10e du brut de la période) et on garde <b>le plus favorable</b> au salarié.','Depuis 2024, un arrêt maladie non professionnel fait aussi acquérir des congés (2 jours ouvrables par mois, 24 max par an).']},
      {h:'L\'arrêt maladie',l:['La Sécurité sociale verse des <b>indemnités journalières (IJSS)</b> après <b>3 jours de carence</b>.','Avec <b>1 an d\'ancienneté</b>, l\'employeur complète le salaire (<b>maintien légal</b>) après 7 jours de carence. La convention collective peut être plus favorable.','En <b>subrogation</b>, l\'employeur maintient le salaire et touche les IJSS à la place du salarié.']},
      {h:'Retenir une absence',l:['Méthode courante : salaire mensuel ÷ heures réelles du mois × heures d\'absence.','Toujours vérifier la méthode prévue par la convention collective.']}],
   k:['Congés payés','Règle du dixième','IJSS','Subrogation','Jours ouvrables']},
  {id:'sortie',i:'📤',t:'Entrées, sorties & DSN',d:'Contrat, fin de contrat, déclarations',
   s:[{h:'L\'embauche',l:['<b>DPAE</b> (déclaration préalable à l\'embauche) : à l\'URSSAF, <b>avant</b> la prise de poste.','Période d\'essai maximale en CDI : <b>2 mois</b> ouvriers/employés, <b>3 mois</b> agents de maîtrise/techniciens, <b>4 mois</b> cadres (renouvelable une fois si un accord de branche le prévoit).']},
      {h:'La fin de contrat',l:['Documents à remettre : <b>certificat de travail</b>, <b>attestation France Travail</b>, <b>reçu pour solde de tout compte</b>.','Fin de CDD : <b>indemnité de fin de contrat = 10 %</b> du brut total (sauf exceptions).','<b>Indemnité légale de licenciement</b> (dès 8 mois d\'ancienneté) : 1/4 de mois de salaire par année jusqu\'à 10 ans, puis 1/3 de mois par année au-delà.','Le solde de tout compte comprend notamment l\'<b>indemnité compensatrice de congés payés</b> non pris.']},
      {h:'La DSN',l:['<b>Déclaration sociale nominative</b> : transmise <b>chaque mois</b> à partir des données de paie.','Échéance : le <b>5</b> du mois suivant (50 salariés et plus) ou le <b>15</b> (moins de 50).','Elle remplace la plupart des anciennes déclarations sociales.']}],
   k:['DPAE','DSN','Solde de tout compte','Indemnité de fin de contrat','Période d\'essai']}
 ],
 lexique:[
  ['Salaire brut','Rémunération totale avant déduction des cotisations salariales.'],
  ['Net à payer','Somme réellement versée au salarié, après cotisations et prélèvement à la source.'],
  ['Montant net social','Montant affiché sur le bulletin qui sert au calcul des aides sociales (RSA, prime d\'activité).'],
  ['Prélèvement à la source','Impôt sur le revenu retenu directement sur le salaire par l\'employeur.'],
  ['SMIC','Salaire minimum interprofessionnel de croissance. 12,02 € brut de l\'heure en 2026.'],
  ['Heures supplémentaires','Heures faites au-delà de 35 h par semaine, payées avec majoration.'],
  ['Convention collective','Accord de branche qui complète le Code du travail : salaires minimums, primes, préavis…'],
  ['Taux horaire','Salaire mensuel divisé par 151,67 heures (pour 35 h par semaine).'],
  ['PMSS','Plafond mensuel de la Sécurité sociale : 4 005 € en 2026. Limite pour certaines cotisations.'],
  ['CSG','Contribution sociale généralisée : 9,2 % sur 98,25 % du brut (6,8 % déductible + 2,4 % non déductible).'],
  ['CRDS','Contribution au remboursement de la dette sociale : 0,5 % sur 98,25 % du brut.'],
  ['URSSAF','Organisme qui collecte la plupart des cotisations de Sécurité sociale.'],
  ['Agirc-Arrco','Régime de retraite complémentaire des salariés du privé.'],
  ['Congés payés','2,5 jours ouvrables acquis par mois de travail, soit 5 semaines par an.'],
  ['Règle du dixième','Indemnité de congés = 1/10e du brut de la période de référence, si plus favorable que le maintien.'],
  ['IJSS','Indemnités journalières de Sécurité sociale versées pendant un arrêt de travail.'],
  ['Subrogation','L\'employeur maintient le salaire et perçoit les IJSS à la place du salarié.'],
  ['Jours ouvrables','Tous les jours de la semaine sauf le dimanche et les jours fériés chômés.'],
  ['DPAE','Déclaration préalable à l\'embauche, faite à l\'URSSAF avant l\'arrivée du salarié.'],
  ['DSN','Déclaration sociale nominative : déclaration mensuelle des données de paie.'],
  ['Solde de tout compte','Document qui liste toutes les sommes versées au salarié à la fin du contrat.'],
  ['Indemnité de fin de contrat','Prime de 10 % du brut total versée à la fin d\'un CDD (dite « de précarité »).'],
  ['Période d\'essai','Début du contrat pendant lequel chacun peut rompre facilement.']
 ],
 quiz:[
  ['bulletin','Le net à payer, c\'est…',['Le net avant impôt moins le prélèvement à la source','Le brut moins les cotisations patronales','Le brut plus les primes','Le salaire de base'],0,'Brut − cotisations salariales = net avant impôt ; − PAS = net à payer.'],
  ['bulletin','Les cotisations salariales d\'un non-cadre représentent environ…',['22 % du brut','5 % du brut','45 % du brut','50 % du brut'],0,'D\'où un net ≈ 78 % du brut.'],
  ['bulletin','Un salarié gagne 2 000 € brut. Son net avant impôt est d\'environ…',['1 560 €','1 900 €','1 100 €','2 440 €'],0,'2 000 × 0,78 ≈ 1 560 €.'],
  ['bulletin','Combien de temps l\'employeur conserve-t-il le double des bulletins ?',['5 ans','1 an','3 mois','10 ans'],0,'5 ans pour l\'employeur, sans limite pour le salarié.'],
  ['bulletin','Le montant net social sert à…',['Calculer les aides sociales','Calculer l\'impôt','Calculer les congés','Calculer la CSG'],0,'RSA, prime d\'activité…'],
  ['bulletin','Les cotisations patronales s\'élèvent environ à…',['40 à 45 % du brut','10 % du brut','22 % du brut','80 % du brut'],0,'Avant réductions de cotisations.'],
  ['temps','La durée légale mensuelle pour 35 h par semaine est de…',['151,67 h','140 h','160 h','35 h'],0,'35 × 52 ÷ 12 = 151,67 h.'],
  ['temps','Le SMIC horaire brut en 2026 est de…',['12,02 €','11,65 €','10,50 €','14,00 €'],0,'Revalorisé de 1,18 % au 1er janvier 2026.'],
  ['temps','Un salaire de 2 275,05 € pour 151,67 h donne un taux horaire de…',['15 €','12 €','18 €','22,75 €'],0,'2 275,05 ÷ 151,67 = 15 €.'],
  ['temps','Sans accord, la 38e heure de la semaine est majorée de…',['25 %','50 %','10 %','0 %'],0,'+25 % de la 36e à la 43e heure.'],
  ['temps','Sans accord, la 45e heure de la semaine est majorée de…',['50 %','25 %','10 %','100 %'],0,'+50 % à partir de la 44e heure.'],
  ['temps','Taux horaire 15 €, 4 heures sup à 25 %. Montant ?',['75 €','60 €','90 €','15 €'],0,'4 × 15 × 1,25 = 75 €.'],
  ['temps','Un accord d\'entreprise peut fixer la majoration des heures sup à…',['10 % minimum','0 %','5 %','Ce qu\'il veut'],0,'Plancher légal : 10 %.'],
  ['temps','Où trouve-t-on souvent les salaires minimums d\'une branche ?',['Dans la convention collective','Dans le bulletin','Dans la DSN','Sur le contrat seulement'],0,'Toujours vérifier la convention.'],
  ['cotis','Le PMSS en 2026 est de…',['4 005 €','3 925 €','1 823 €','48 060 €'],0,'48 060 € est le plafond annuel (PASS).'],
  ['cotis','L\'assiette de la CSG est de…',['98,25 % du brut','100 % du brut','78 % du brut','50 % du brut'],0,'Abattement de 1,75 % pour frais professionnels.'],
  ['cotis','Le taux de la CSG déductible est de…',['6,8 %','2,4 %','0,5 %','9,2 %'],0,'6,8 % déductible + 2,4 % non déductible = 9,2 %.'],
  ['cotis','Le taux de la CRDS est de…',['0,5 %','2,4 %','6,8 %','1 %'],0,'0,5 % sur 98,25 % du brut.'],
  ['cotis','L\'assurance chômage est payée…',['Uniquement par l\'employeur','Uniquement par le salarié','Moitié-moitié','Par l\'État'],0,'Plus de part salariale depuis 2018.'],
  ['cotis','La retraite complémentaire des salariés du privé, c\'est…',['L\'Agirc-Arrco','L\'URSSAF','La CPAM','France Travail'],0,'Cotisations sur T1 et T2.'],
  ['cotis','La mutuelle d\'entreprise est financée par l\'employeur à au moins…',['50 %','25 %','100 %','10 %'],0,'Minimum légal : la moitié.'],
  ['cotis','Une cotisation « plafonnée » s\'applique…',['Jusqu\'au plafond de la Sécurité sociale','Sur tout le salaire','Seulement aux cadres','Seulement au-dessus du plafond'],0,'C\'est la tranche A / T1.'],
  ['absences','Combien de jours ouvrables de congés acquiert-on par mois ?',['2,5','2','3','1,5'],0,'2,5 × 12 = 30 jours ouvrables.'],
  ['absences','Un salarié a travaillé 6 mois. Il a acquis…',['15 jours ouvrables','12 jours ouvrables','30 jours ouvrables','6 jours ouvrables'],0,'6 × 2,5 = 15.'],
  ['absences','Brut de la période de référence : 24 000 €. Selon la règle du dixième, l\'indemnité de congés annuelle est…',['2 400 €','240 €','2 000 €','24 000 €'],0,'24 000 ÷ 10 = 2 400 €.'],
  ['absences','Pour l\'indemnité de congés, on retient…',['Le plus favorable entre maintien et dixième','Toujours le maintien','Toujours le dixième','Le moins élevé'],0,'On compare les deux méthodes.'],
  ['absences','Combien de jours de carence avant les IJSS en maladie ?',['3','7','1','0'],0,'3 jours de carence pour la Sécurité sociale.'],
  ['absences','Le maintien de salaire légal par l\'employeur demande…',['1 an d\'ancienneté','3 mois d\'ancienneté','Aucune ancienneté','5 ans d\'ancienneté'],0,'Avec 7 jours de carence (la convention peut faire mieux).'],
  ['absences','La subrogation, c\'est quand…',['L\'employeur touche les IJSS à la place du salarié','Le salarié ne touche rien','La CPAM paie le salaire entier','On retient l\'absence deux fois'],0,'L\'employeur maintient le salaire et se fait rembourser.'],
  ['absences','Les jours ouvrables sont…',['Tous les jours sauf dimanche et jours fériés','Du lundi au vendredi','Les jours travaillés dans l\'entreprise','Tous les jours'],0,'Les jours ouvrés, eux, sont les jours travaillés (souvent du lundi au vendredi).'],
  ['sortie','La DPAE se fait…',['Avant l\'embauche','Le premier mois','À la fin du contrat','Chaque année'],0,'Déclaration préalable à l\'embauche, auprès de l\'URSSAF.'],
  ['sortie','La DSN est transmise…',['Chaque mois','Chaque année','À l\'embauche seulement','Chaque trimestre'],0,'Le 5 ou le 15 du mois suivant.'],
  ['sortie','Une entreprise de 30 salariés transmet sa DSN au plus tard le…',['15 du mois suivant','5 du mois suivant','1er du mois suivant','31 du mois'],0,'Moins de 50 salariés : le 15.'],
  ['sortie','L\'indemnité de fin de CDD est de…',['10 % du brut total','5 %','20 %','1 mois de salaire'],0,'Sauf exceptions (emploi saisonnier, CDD étudiant…).'],
  ['sortie','Un CDD a rapporté 8 000 € brut. L\'indemnité de fin de contrat est de…',['800 €','80 €','1 600 €','400 €'],0,'8 000 × 10 % = 800 €.'],
  ['sortie','Salaire de référence 2 000 €, 6 ans d\'ancienneté. Indemnité légale de licenciement ?',['3 000 €','2 000 €','12 000 €','4 000 €'],0,'2 000 × 1/4 × 6 = 3 000 €.'],
  ['sortie','La période d\'essai maximale d\'un employé en CDI (sans renouvellement) est de…',['2 mois','1 mois','4 mois','6 mois'],0,'2 mois employés, 3 mois techniciens, 4 mois cadres.'],
  ['sortie','Lequel n\'est PAS remis à la fin du contrat ?',['La DPAE','Le certificat de travail','L\'attestation France Travail','Le solde de tout compte'],0,'La DPAE se fait à l\'embauche.']
 ],
 vf:[
  ['Le net à payer est plus élevé que le brut.',false,'C\'est l\'inverse : on retire les cotisations.'],
  ['Le SMIC horaire brut 2026 est de 12,02 €.',true,'1 823,03 € par mois pour 35 h.'],
  ['La 36e heure est une heure supplémentaire.',true,'Au-delà de 35 h.'],
  ['Le salarié paie une cotisation d\'assurance chômage.',false,'Seul l\'employeur la paie depuis 2018.'],
  ['La CSG est calculée sur 98,25 % du brut.',true,'Abattement de 1,75 %.'],
  ['On acquiert 2,5 jours ouvrables de congés par mois.',true,'30 jours ouvrables par an.'],
  ['Pour les congés, on applique toujours le maintien de salaire.',false,'On compare avec la règle du dixième.'],
  ['La DPAE se fait après l\'embauche.',false,'Avant la prise de poste.'],
  ['La DSN est mensuelle.',true,'Chaque mois.'],
  ['La mutuelle peut être payée entièrement par le salarié.',false,'L\'employeur paie au moins 50 %.'],
  ['Le PMSS 2026 est de 4 005 €.',true,'48 060 € par an.'],
  ['L\'indemnité de fin de CDD est de 10 %.',true,'Du brut total versé.'],
  ['Le salarié doit garder ses bulletins 5 ans seulement.',false,'Il les garde sans limite de durée.'],
  ['Les jours ouvrables incluent le samedi.',true,'Tous les jours sauf dimanche et jours fériés.'],
  ['La subrogation permet à l\'employeur de percevoir les IJSS.',true,'Il maintient le salaire et se fait rembourser.']
 ],
 ordre:[
  {t:'Du brut au net à payer',s:['Salaire de base','+ heures sup et primes','− absences','= salaire brut','− cotisations salariales','= net avant impôt','− prélèvement à la source','= net à payer']},
  {t:'Le cycle mensuel de paie',s:['Collecter les variables (absences, heures sup, primes)','Saisir dans le logiciel de paie','Contrôler les bulletins','Payer les salaires','Transmettre la DSN']},
  {t:'Embaucher un salarié',s:['Choisir le candidat','Faire la DPAE','Accueillir le salarié le premier jour','Saisir ses heures et absences du mois','Établir le premier bulletin','Inclure le salarié dans la DSN du mois']}
 ]
};
