/* Soudeur Pro — contenu (titres pro Soudeur assembleur industriel / Soudeur TIG électrode enrobée)
   À faire relire par un formateur soudure avant publication. */
const C={
 id:'soudeur',app:'Soudeur Pro',icon:'🔥',
 sousTitre:'Les bases du titre professionnel de soudeur, en fiches courtes.',
 theme:{pri:'#ff8a3d',pri2:'#c95a10'},
 pub:{actif:true,toutesLes:3},
 modules:[
  {id:'procedes',i:'⚙️',t:'Les procédés de soudage',d:'Électrode enrobée, MAG, MIG, TIG, chalumeau',
   s:[{h:'Les numéros de procédés (ISO 4063)',l:['<b>111</b> : électrode enrobée (arc manuel, « à la baguette »).','<b>135</b> : MAG, fil plein sous gaz actif.','<b>131</b> : MIG, fil plein sous gaz inerte.','<b>141</b> : TIG, électrode de tungstène non fusible sous gaz inerte.','<b>311</b> : soudage oxyacétylénique (chalumeau).']},
      {h:'Quel procédé pour quoi ?',l:['<b>Électrode enrobée</b> : chantier, extérieur, matériel simple.','<b>MAG</b> : production rapide sur acier.','<b>MIG</b> : aluminium, inox.','<b>TIG</b> : soudures précises et propres, tuyauterie, inox, aluminium.']},
      {h:'Les gaz de protection',l:['<b>TIG et MIG</b> : gaz inerte, le plus souvent <b>argon</b>.','<b>MAG</b> : gaz actif, mélange <b>argon + CO₂</b> (ou CO₂ pur).','Le gaz protège le bain de fusion de l\'air (oxygène, azote).']}],
   k:['Arc électrique','Bain de fusion','TIG','MAG','MIG','Électrode enrobée']},
  {id:'secu',i:'🦺',t:'Sécurité au poste',d:'Rayonnement, fumées, incendie, bouteilles de gaz',
   s:[{h:'Les risques du soudage',l:['<b>Rayonnement</b> UV et infrarouge : « coup d\'arc » aux yeux, brûlures de la peau.','<b>Fumées</b> toxiques : aspiration obligatoire au plus près de la soudure.','<b>Incendie</b> : projections incandescentes, permis de feu sur site.','<b>Électrique</b> : ne jamais travailler avec des gants mouillés.']},
      {h:'Les EPI du soudeur',l:['Masque avec <b>filtre teinté</b> adapté à l\'intensité (souvent teinte 9 à 13).','Gants en cuir à manchette, veste ou tablier en cuir.','Chaussures de sécurité, vêtements en coton (pas de synthétique).']},
      {h:'Les bouteilles de gaz',l:['Toujours <b>attachées debout</b>, robinet fermé après usage.','Couleur de l\'ogive : <b>blanc</b> = oxygène, <b>marron</b> = acétylène, <b>vert foncé</b> = argon, <b>gris</b> = CO₂.','Jamais de graisse sur un raccord d\'oxygène (risque d\'explosion).']}],
   k:['EPI','Fumées de soudage','Permis de feu','Coup d\'arc']},
  {id:'prepa',i:'📐',t:'Préparer l\'assemblage',d:'Lecture de plan, chanfrein, pointage, positions',
   s:[{h:'Préparer les bords',l:['Nettoyer : enlever rouille, peinture, graisse.','<b>Chanfreiner</b> les pièces épaisses (souvent en V) pour que la soudure pénètre.','Laisser un <b>écartement</b> régulier entre les pièces.']},
      {h:'Pointer avant de souder',l:['Le <b>pointage</b> = petits points de soudure qui maintiennent les pièces.','Il limite les <b>déformations</b> pendant le soudage.','On vérifie l\'équerrage et l\'alignement après pointage.']},
      {h:'Les positions de soudage',l:['<b>PA</b> : à plat.','<b>PB</b> : angle à plat.','<b>PC</b> : en corniche (horizontale).','<b>PF</b> : verticale montante.','<b>PE</b> : au plafond.']}],
   k:['Chanfrein','Pointage','Déformation']},
  {id:'reglages',i:'🎛️',t:'Réglages & mise en œuvre',d:'Intensité, polarité, électrodes, tungstène',
   s:[{h:'Électrodes enrobées',l:['<b>Rutile</b> : facile à utiliser, bel aspect.','<b>Basique</b> : meilleures caractéristiques mécaniques ; à <b>étuver</b> (garder au sec).','Plus l\'électrode est grosse, plus l\'intensité est élevée.']},
      {h:'Le TIG',l:['Acier et inox : <b>courant continu</b>, électrode de tungstène au pôle <b>moins</b>.','Aluminium : <b>courant alternatif</b> (pour casser la couche d\'oxyde).','Le métal d\'apport est ajouté à la main avec une baguette.']},
      {h:'Le bon réglage',l:['Intensité trop faible : collage, manque de pénétration.','Intensité trop forte : caniveaux, perçage, projections.','Garder une vitesse et un angle de torche réguliers.']}],
   k:['Tungstène','Pénétration','Métal d\'apport']},
  {id:'controle',i:'🔍',t:'Défauts & contrôles',d:'Reconnaître un défaut, contrôler une soudure',
   s:[{h:'Les défauts courants',l:['<b>Porosités</b> (soufflures) : bulles de gaz dans le cordon.','<b>Caniveau</b> : creux le long du cordon.','<b>Manque de pénétration</b> : la soudure ne traverse pas.','<b>Collage</b> : le métal est posé mais pas fondu avec la pièce.','<b>Fissures</b> et <b>inclusions de laitier</b>.']},
      {h:'Les contrôles',l:['<b>Contrôle visuel</b> : toujours en premier.','<b>Ressuage</b> : révèle les fissures qui débouchent en surface.','<b>Radiographie</b> et <b>ultrasons</b> : défauts internes.','La qualification du soudeur suit la norme <b>NF EN ISO 9606-1</b> (aciers).']}],
   k:['Porosité','Caniveau','Laitier','Ressuage']}
 ],
 lexique:[
  ['Arc électrique','Décharge électrique entre l\'électrode et la pièce qui produit la chaleur de fusion.'],
  ['Bain de fusion','Zone de métal liquide créée par la source de chaleur pendant le soudage.'],
  ['TIG','Tungsten Inert Gas (procédé 141) : électrode de tungstène non fusible sous gaz inerte.'],
  ['MAG','Metal Active Gas (procédé 135) : fil fusible sous gaz actif, souvent argon + CO₂.'],
  ['MIG','Metal Inert Gas (procédé 131) : fil fusible sous gaz inerte (argon), pour alu et inox.'],
  ['Électrode enrobée','Baguette métallique recouverte d\'un enrobage qui fond et protège le bain (procédé 111).'],
  ['EPI','Équipements de Protection Individuelle : masque, gants cuir, tablier, chaussures…'],
  ['Fumées de soudage','Particules et gaz toxiques dégagés au soudage. À capter par aspiration.'],
  ['Permis de feu','Document obligatoire pour souder dans une zone à risque d\'incendie.'],
  ['Coup d\'arc','Brûlure de l\'œil causée par les UV de l\'arc. Très douloureux, quelques heures après.'],
  ['Chanfrein','Biseau usiné sur le bord d\'une pièce épaisse pour permettre une bonne pénétration.'],
  ['Pointage','Petits points de soudure qui maintiennent les pièces avant le soudage final.'],
  ['Déformation','Changement de forme des pièces dû à la dilatation puis au retrait du métal.'],
  ['Tungstène','Métal très réfractaire utilisé pour l\'électrode non fusible en TIG.'],
  ['Pénétration','Profondeur à laquelle la soudure fond dans les pièces assemblées.'],
  ['Métal d\'apport','Métal ajouté (fil, baguette, électrode) qui forme le cordon de soudure.'],
  ['Porosité','Défaut : bulles de gaz emprisonnées dans le cordon (aussi appelée soufflure).'],
  ['Caniveau','Défaut : creux le long du bord du cordon, souvent dû à une intensité trop forte.'],
  ['Laitier','Croûte formée par l\'enrobage fondu. À retirer entre deux passes.'],
  ['Ressuage','Contrôle avec un liquide coloré qui révèle les fissures débouchantes.'],
  ['Cordon','Le dépôt de métal visible qui forme la soudure.'],
  ['Passe','Un cordon déposé en une fois. Une soudure épaisse demande plusieurs passes.']
 ],
 quiz:[
  ['procedes','Le procédé 141 est…',['Le TIG','Le MAG','L\'électrode enrobée','Le chalumeau'],0,'141 = TIG selon la norme ISO 4063.'],
  ['procedes','Le procédé 111 est…',['L\'électrode enrobée','Le MIG','Le TIG','Le soudage laser'],0,'111 = soudage à l\'arc avec électrode enrobée.'],
  ['procedes','En MAG, le gaz est…',['Actif (argon + CO₂)','Inerte (argon pur)','De l\'oxygène','De l\'acétylène'],0,'MAG = Metal Active Gas.'],
  ['procedes','Quel procédé utilise une électrode non fusible ?',['TIG','MAG','MIG','111'],0,'L\'électrode de tungstène ne fond pas en TIG.'],
  ['procedes','Le rôle du gaz de protection est de…',['Protéger le bain de l\'air','Refroidir la pièce','Augmenter l\'intensité','Nettoyer la torche'],0,'L\'oxygène et l\'azote de l\'air abîment la soudure.'],
  ['secu','Le « coup d\'arc » touche…',['Les yeux','Les mains','Les poumons','Les oreilles'],0,'C\'est une brûlure de l\'œil par les UV.'],
  ['secu','Quelle ogive de bouteille pour l\'acétylène ?',['Marron','Blanche','Vert foncé','Grise'],0,'Marron = acétylène, blanc = oxygène.'],
  ['secu','Quelle ogive de bouteille pour l\'oxygène ?',['Blanche','Marron','Noire','Jaune'],0,'Oxygène = ogive blanche.'],
  ['secu','Contre les fumées de soudage, on utilise…',['Une aspiration à la source','Un ventilateur de plafond','Des gants','Rien, c\'est inoffensif'],0,'On capte les fumées au plus près de la soudure.'],
  ['secu','Il est interdit de mettre de la graisse sur…',['Un raccord d\'oxygène','Une brosse métallique','Un étau','Une meuleuse'],0,'Oxygène + graisse = risque d\'inflammation violente.'],
  ['prepa','Pourquoi chanfreiner une pièce épaisse ?',['Pour une bonne pénétration','Pour la décorer','Pour économiser du gaz','Pour la peindre'],0,'Le chanfrein permet à la soudure de fondre toute l\'épaisseur.'],
  ['prepa','Le pointage sert à…',['Maintenir les pièces et limiter les déformations','Contrôler la soudure','Nettoyer les bords','Refroidir le métal'],0,'On pointe avant de souder.'],
  ['prepa','La position PF est…',['Verticale montante','À plat','Au plafond','En corniche'],0,'PF = verticale montante.'],
  ['prepa','La position PA est…',['À plat','Au plafond','Verticale descendante','En corniche'],0,'PA = à plat, la plus facile.'],
  ['reglages','Pour souder l\'aluminium en TIG, on utilise…',['Le courant alternatif','Le courant continu électrode au moins','Le courant continu électrode au plus','Une électrode enrobée'],0,'L\'alternatif casse la couche d\'oxyde d\'aluminium.'],
  ['reglages','Une électrode basique doit être…',['Étuvée (gardée au sec)','Mouillée avant usage','Chauffée au chalumeau','Rangée au frigo'],0,'L\'humidité provoque des fissures et porosités.'],
  ['reglages','Une intensité trop forte provoque souvent…',['Des caniveaux','Un collage','Un manque de pénétration','Rien'],0,'Trop fort = caniveaux, perçage, projections.'],
  ['reglages','Une intensité trop faible provoque souvent…',['Un collage','Des caniveaux','Un perçage','Des projections'],0,'Pas assez de chaleur : le métal ne fond pas avec la pièce.'],
  ['controle','Des bulles dans le cordon, ce sont des…',['Porosités','Caniveaux','Fissures','Collages'],0,'Porosités ou soufflures.'],
  ['controle','Quel contrôle révèle les fissures débouchantes ?',['Le ressuage','La pesée','Le pliage à la main','Le contrôle au marteau'],0,'Le liquide pénétrant révèle les fissures en surface.'],
  ['controle','Le premier contrôle d\'une soudure est…',['Le contrôle visuel','La radiographie','Les ultrasons','Le ressuage'],0,'On regarde toujours en premier.'],
  ['controle','Le laitier doit être…',['Retiré entre deux passes','Laissé en place','Soudé par-dessus','Peint'],0,'Sinon : inclusion de laitier dans la soudure.']
 ],
 vf:[
  ['En TIG, l\'électrode de tungstène fond dans le bain.',false,'Elle est non fusible.'],
  ['Le MAG utilise un gaz actif.',true,'Argon + CO₂ ou CO₂ pur.'],
  ['On peut souder avec des gants mouillés.',false,'Risque électrique : gants secs obligatoires.'],
  ['Les vêtements synthétiques sont conseillés pour souder.',false,'Ils fondent : coton ou cuir.'],
  ['Une bouteille de gaz doit être attachée debout.',true,'Pour éviter la chute et la casse du robinet.'],
  ['Le pointage limite les déformations.',true,'Il maintient les pièces en position.'],
  ['La position PE, c\'est à plat.',false,'PE = au plafond. À plat, c\'est PA.'],
  ['L\'aluminium se soude en TIG en courant alternatif.',true,'Pour casser la couche d\'oxyde.'],
  ['Une électrode rutile est réputée facile à utiliser.',true,'Bel aspect, amorçage facile.'],
  ['Le ressuage détecte les défauts internes profonds.',false,'Seulement les défauts qui débouchent en surface.'],
  ['Le laitier se retire entre deux passes.',true,'Sinon il reste piégé dans la soudure.'],
  ['Un caniveau est souvent dû à une intensité trop forte.',true,'Le bord de la pièce fond trop.'],
  ['Les fumées de soudage sont sans danger.',false,'Elles sont toxiques : aspiration obligatoire.'],
  ['L\'ogive blanche correspond à l\'oxygène.',true,'Marron = acétylène.']
 ],
 ordre:[
  {t:'Réaliser une soudure bout à bout',s:['Lire le plan et le DMOS','Nettoyer et chanfreiner les bords','Pointer les pièces','Souder la passe de racine','Retirer le laitier et brosser','Souder les passes de remplissage','Contrôler visuellement']},
  {t:'Mettre en service un poste au chalumeau',s:['Vérifier les bouteilles attachées','Ouvrir les robinets des bouteilles','Régler les détendeurs','Ouvrir l\'acétylène et allumer','Ouvrir l\'oxygène et régler la flamme']}
 ]
};
