/* JEU — Dépannages avec bon de travail. Pressions = valeurs CoolProp (bar relatifs). */
C.diag=[
 {id:"split-fuite",t:"Le split refroidit de moins en moins",ic:"🌡️",niv:1,
  bon:{lieu:"Appartement — split mural R32 (1,1 kg), séjour",qui:"M. Lambert",heure:"Lundi 14 h, 32 °C dehors",prio:2,pb:"La clim souffle à peine frais depuis 15 jours. Elle marchait bien l'été dernier.",contrainte:"Un bébé dans le logement : le client veut une solution rapide."},
  etapes:[
   {q:"Avant de brancher le manifold, tu vérifies…",o:[["Les filtres de l'unité intérieure, les ventilateurs et le condenseur",true,"Filtres propres, ventilateurs OK, condenseur propre. Le problème est donc probablement dans le circuit."],["Rien, tu ajoutes directement du fluide",false,"On ne recharge jamais sans diagnostic : la loi impose de trouver et réparer les fuites."],["La télécommande seulement",false,"Utile mais insuffisant : il faut contrôler l'aéraulique (filtres, ventilateurs, échangeurs)."]]},
   {info:"Mesures stabilisées : BP 4,8 bar (≈ −10 °C), HP 18,3 bar (≈ 30 °C), aspiration +8 °C, ligne liquide +30 °C.",q:"Calcule : surchauffe et sous-refroidissement ?",o:[["Surchauffe 18 K, sous-refroidissement 0 K",true,"Surchauffe 8 − (−10) = 18 K (beaucoup trop), sous-refroidissement 30 − 30 = 0 K (rien). Avec BP et HP basses : signature d'un manque de fluide."],["Surchauffe 8 K, sous-refroidissement 30 K",false,"Surchauffe = T aspiration − T évaporation = 8 − (−10) = 18 K."],["Surchauffe 2 K, sous-refroidissement 12 K",false,"Reprends les tables : 4,8 bar ≈ −10 °C et 18,3 bar ≈ 30 °C."]]},
   {q:"Un manque de fluide sur un circuit scellé, cela signifie…",o:[["Qu'il y a une fuite à trouver",true,"Un circuit étanche ne perd pas de fluide."],["Que le fluide « s'use »",false,"Le fluide ne s'use pas : il ne disparaît que par une fuite."],["Que c'est normal tous les ans",false,"Non : un circuit étanche garde sa charge."]]},
   {info:"Au détecteur électronique puis au produit moussant : bulles sur le raccord flare de la ligne liquide, à l'unité intérieure.",q:"Comment répares-tu ?",o:[["Récupérer le fluide, refaire l'évasement, serrer au couple, essai azote, vide, charge complète au poids",true,"L'ancien évasement était fissuré. Nouveau dudgeon, essai à l'azote OK, vide qui tient, charge de 1,1 kg au poids."],["Resserrer l'écrou très fort et rajouter du fluide",false,"Un évasement qui fuit est souvent fissuré : trop serrer l'aggrave. Et on ne complète pas sans savoir ce qu'il reste."],["Mettre de la colle sur le raccord",false,"Les colles ne sont pas une réparation durable ni conforme."]]},
   {q:"Pour finir :",o:[["Mesures de contrôle, fiche d'intervention Cerfa 15497 (fluide récupéré et chargé), recontrôle d'étanchéité entre 24 h et 1 mois",true,"Surchauffe 6 K, sous-refroidissement 5 K, air soufflé 10 K plus froid. Fiche remplie, recontrôle programmé."],["Partir sans rien noter",false,"Toute manipulation de fluide se trace sur la fiche d'intervention."],["Laisser le manifold branché",false,"On débranche, on remet les bouchons de valves et on contrôle leur étanchéité."]]}],
  fin:"Manque de fluide dû à un raccord flare fissuré (BP basse, surchauffe 18 K, sous-refroidissement nul). Récupération, nouvel évasement, essai à l'azote, tirage au vide, charge complète au poids, mesures, fiche d'intervention et recontrôle programmé.",
  retenir:"Surchauffe haute + sous-refroidissement faible = manque de fluide = fuite à réparer."},

 {id:"condenseur",t:"La chambre froide part en sécurité HP",ic:"🌡️",niv:1,
  bon:{lieu:"Boulangerie — chambre froide positive R404A, groupe sur la cour",qui:"Le boulanger",heure:"Mardi 15 h, 30 °C dehors",prio:1,pb:"La chambre est à +9 °C. Le compresseur s'arrête et redémarre, une alarme HP s'affiche.",contrainte:"Les pâtisseries doivent rester au froid."},
  etapes:[
   {q:"Une sécurité HP qui déclenche : premières pistes ?",o:[["Condenseur sale ou mal ventilé, ventilateur de condenseur en panne",true,"Tu regardes le groupe : le condenseur est couvert de farine collée et de poussière."],["Manque de fluide",false,"Un manque de fluide fait plutôt baisser la HP."],["Évaporateur givré",false,"Un évaporateur givré fait baisser la BP, pas monter la HP."]]},
   {info:"Mesures : HP 22,1 bar (R404A, bulle ≈ 50 °C) avec 30 °C dehors.",q:"Que penses-tu de l'écart condensation / air extérieur ?",o:[["20 K, c'est trop : le condenseur évacue mal la chaleur",true,"On attend plutôt 10 à 15 K."],["C'est parfait",false,"20 K d'écart, c'est trop élevé pour un condenseur à air propre."],["Il est trop faible",false,"Au contraire, il est trop grand."]]},
   {q:"Ta réparation :",o:[["Consigner, nettoyer le condenseur (produit adapté, rinçage à basse pression), redresser les ailettes",true,"Le condenseur est propre. Le ventilateur tourne bien."],["Ajouter du fluide",false,"Le fluide n'est pas en cause : la HP est haute à cause du condenseur."],["Régler le pressostat HP plus haut",false,"Jamais : c'est une sécurité."]]},
   {q:"Après remise en route :",o:[["Mesurer à nouveau et conseiller un nettoyage régulier",true,"HP 17,3 bar (≈ 40 °C) : écart de 10 K. La chambre redescend à +3 °C. Tu proposes un nettoyage tous les 3 mois vu la farine."],["Partir tout de suite",false,"On contrôle toujours le résultat."],["Mettre le groupe dans un local fermé",false,"Le condenseur a besoin d'air : un local fermé aggraverait le problème."]]}],
  fin:"Condenseur encrassé (farine et poussière) : HP à 22,1 bar, écart de 20 K avec l'air, déclenchements HP. Nettoyage, contrôle : HP 17,3 bar, écart 10 K, température revenue. Conseil d'entretien trimestriel.",
  retenir:"HP haute + grand écart avec l'air extérieur = problème de condenseur (sale, ventilateur, air recyclé)."},

 {id:"ventilo-condenseur",t:"Le pressostat HP déclenche l'après-midi",ic:"🌀",niv:2,
  bon:{lieu:"Supérette — armoire frigorifique à groupe logé R290",qui:"Gérante",heure:"Jeudi 16 h",prio:2,pb:"L'armoire se met en défaut HP tous les après-midis ; il faut réarmer.",contrainte:"Fluide inflammable (propane, A3)."},
  etapes:[
   {q:"Groupe logé au propane : précaution avant d'ouvrir le capot ?",o:[["Couper, consigner, vérifier l'absence de fuite au détecteur adapté, pas de source d'inflammation",true,"Détecteur compatible propane : aucune fuite. Zone dégagée."],["Allumer une lampe à flamme pour mieux voir",false,"Jamais de flamme avec un fluide A3."],["Aucune précaution particulière",false,"Le R290 est très inflammable : précautions obligatoires."]]},
   {info:"En fonctionnement, le ventilateur du condenseur tourne très lentement et chauffe ; il démarre si on l'aide à la main.",q:"Composant suspect ?",o:[["Le condensateur du moteur de ventilateur",true,"Mesure hors tension (après décharge) : 0,8 µF au lieu de 2 µF. Il a perdu sa capacité."],["Le compresseur",false,"C'est le ventilateur qui tourne mal : le compresseur n'est pas en cause pour l'instant."],["Le détendeur",false,"Le détendeur n'a rien à voir avec la ventilation du condenseur."]]},
   {q:"Réparation :",o:[["Remplacer le condensateur par un modèle de même capacité et même tension",true,"Le ventilateur tourne à pleine vitesse. HP revenue à la normale."],["Mettre un condensateur deux fois plus gros",false,"La capacité est fixée par le fabricant du moteur."],["Shunter le pressostat HP",false,"Interdit : c'est une sécurité."]]},
   {q:"Pourquoi le défaut arrivait surtout l'après-midi ?",o:[["Il fait plus chaud : le condenseur mal ventilé n'arrivait plus à évacuer la chaleur",true,"Le matin, l'air plus frais compensait le manque de ventilation."],["Parce que la gérante ouvre la porte",false,"Ça joue un peu, mais la cause principale était la ventilation du condenseur."],["Par hasard",false,"Les pannes ont toujours une cause."]]}],
  fin:"Condensateur du ventilateur de condenseur hors service (0,8 µF au lieu de 2 µF) : ventilation insuffisante, HP trop haute aux heures chaudes. Remplacement à l'identique, intervention conduite avec les précautions propres au R290.",
  retenir:"Un pressostat HP qui déclenche se dépanne côté condenseur : propreté, ventilateur, condensateur, air chaud recyclé."},

 {id:"compresseur-demarre-pas",t:"Le compresseur claque et ne démarre pas",ic:"⚡",niv:2,
  bon:{lieu:"Restaurant — armoire positive, compresseur monophasé",qui:"Le chef",heure:"Samedi 11 h",prio:1,pb:"On entend un « clac » toutes les quelques minutes, le compresseur ne démarre pas, il est très chaud.",contrainte:"Service de midi dans une heure."},
  etapes:[
   {q:"Le « clac » régulier et le compresseur chaud, c'est probablement…",o:[["La protection thermique (Klixon) qui coupe puis réenclenche",true,"Le compresseur essaie de démarrer, force, chauffe, et sa protection coupe."],["Le thermostat",false,"Le thermostat ne fait pas chauffer le compresseur."],["Le détendeur",false,"Le détendeur ne fait pas de bruit électrique."]]},
   {info:"Hors tension, après décharge du condensateur : C-R = 2,1 Ω ; C-S = 4,9 Ω ; R-S = 7,0 Ω ; isolement bornes/carcasse > 100 MΩ.",q:"Les bobinages sont-ils bons ?",o:[["Oui : R-S = C-R + C-S, pas de coupure, isolement correct",true,"Le moteur est sain. On cherche dans les composants de démarrage."],["Non, le bobinage de démarrage est coupé",false,"Un bobinage coupé donnerait une valeur infinie."],["Non, il est à la masse",false,"L'isolement est supérieur à 100 MΩ : pas de défaut à la masse."]]},
   {q:"Composant de démarrage à tester en priorité ?",o:[["Le condensateur de démarrage (et le relais de démarrage)",true,"Le condensateur affiche 0 µF : il est hors service."],["Le pressostat HP",false,"Le compresseur reçoit la tension : la chaîne de commande fonctionne."],["Le voyant liquide",false,"Aucun rapport avec le démarrage électrique."]]},
   {q:"Et avant de redémarrer :",o:[["Remplacer à l'identique, laisser refroidir le compresseur, vérifier les pressions (équilibrées ?) et l'intensité au démarrage",true,"Le compresseur démarre normalement, intensité conforme. Tu expliques au chef que le compresseur a été préservé."],["Redémarrer immédiatement, même brûlant",false,"Il faut laisser la protection thermique se refroidir."],["Remplacer le compresseur par précaution",false,"Le moteur est sain : on ne change pas une pièce chère inutilement."]]}],
  fin:"Condensateur de démarrage hors service : le compresseur n'arrivait pas à démarrer et sa protection thermique coupait. Bobinages et isolement contrôlés sains, condensateur remplacé à l'identique, démarrage et intensité conformes.",
  retenir:"Avant de condamner un compresseur, on mesure ses bobinages et son isolement, et on teste les composants de démarrage."},

 {id:"evaporateur-glace",t:"La chambre négative remonte en température",ic:"🧊",niv:2,
  bon:{lieu:"Traiteur — chambre froide négative R404A, −20 °C",qui:"Responsable de production",heure:"Lundi 7 h 30",prio:1,pb:"La chambre est à −8 °C. On voit un bloc de glace sur l'évaporateur.",contrainte:"200 kg de produits surgelés."},
  etapes:[
   {q:"Un évaporateur pris en glace : première piste ?",o:[["Un défaut de dégivrage",true,"Le régulateur lance bien les dégivrages, mais la température de fin de dégivrage n'est jamais atteinte."],["Un excès de fluide",false,"L'excès de fluide ne fabrique pas de glace."],["Un compresseur trop puissant",false,"Ce n'est pas une cause de prise en glace."]]},
   {q:"Le dégivrage est électrique. Que mesures-tu ?",o:[["Consigner, puis mesurer les résistances de dégivrage à l'ohmmètre",true,"Deux résistances à 55 Ω, une troisième infinie : coupée."],["La pression HP",false,"Le dégivrage électrique se contrôle à l'ohmmètre."],["La surchauffe uniquement",false,"La surchauffe ne dit rien sur les résistances."]]},
   {q:"Que fais-tu des produits et de la glace ?",o:[["Prévenir le client pour transférer les produits, dégivrer manuellement sans outil coupant",true,"Produits transférés dans un congélateur de secours. Glace fondue au dégivrage forcé et à l'eau tiède, sans pic ni tournevis."],["Casser la glace au tournevis",false,"On perce facilement un tube de l'évaporateur : fuite assurée."],["Laisser tel quel",false,"La glace empêche l'air de passer : la chambre ne redescendra pas."]]},
   {q:"Après remplacement de la résistance, tu vérifies aussi…",o:[["L'évacuation des condensats (cordon chauffant) et la sonde de fin de dégivrage",true,"Le cordon chauffant de l'évacuation était aussi coupé : l'eau regelait. Les deux sont remplacés."],["Le filtre à air du bureau",false,"Aucun rapport."],["Rien d'autre",false,"Un évacuation gelée ferait recommencer la panne."]]}],
  fin:"Résistance de dégivrage coupée et cordon chauffant d'évacuation hors service : dégivrages incomplets, évaporateur pris en glace. Remplacement des deux, dégivrage manuel sans outil, produits mis à l'abri, chambre revenue à −20 °C.",
  retenir:"Évaporateur en glace : contrôler résistances, sonde de fin, programmation et évacuation chauffée avant d'accuser le fluide."},

 {id:"restriction",t:"La vitrine refroidit mal malgré une charge correcte",ic:"🥗",niv:3,
  bon:{lieu:"Supermarché — vitrine à détendeur thermostatique, R134a",qui:"Responsable de rayon",heure:"Mercredi 10 h",prio:2,pb:"La vitrine est à +9 °C au lieu de +3 °C. Un collègue a « déjà rajouté du fluide » la semaine dernière.",contrainte:"Rayon frais."},
  etapes:[
   {info:"Mesures : BP 0,3 bar (≈ −20 °C), aspiration +2 °C, HP 9,2 bar (≈ 40 °C), ligne liquide +28 °C. Filtre déshydrateur nettement plus froid en sortie qu'en entrée, bulles au voyant après le filtre.",q:"Surchauffe et sous-refroidissement ?",o:[["Surchauffe 22 K, sous-refroidissement 12 K",true,"2 − (−20) = 22 K ; 40 − 28 = 12 K. BP basse, surchauffe haute… et sous-refroidissement élevé."],["Surchauffe 2 K, sous-refroidissement 28 K",false,"Surchauffe = T aspiration − T évaporation = 2 − (−20) = 22 K."],["Surchauffe 22 K, sous-refroidissement 0 K",false,"Sous-refroidissement = 40 − 28 = 12 K."]]},
   {q:"BP basse, surchauffe haute, sous-refroidissement élevé, filtre froid en sortie :",o:[["Une restriction : le filtre déshydrateur est colmaté",true,"Le fluide s'accumule avant le filtre (sous-refroidissement élevé) et manque après (surchauffe élevée)."],["Un manque de fluide",false,"Un manque de fluide donnerait un sous-refroidissement faible."],["Un excès de fluide",false,"L'excès donnerait une BP normale ou haute et une surchauffe faible."]]},
   {q:"Et le fluide « rajouté » la semaine dernière ?",o:[["La charge est probablement trop élevée maintenant : on récupère, on change le filtre, on recharge au poids",true,"Ajouter du fluide sur une restriction n'arrange rien et surcharge le circuit."],["Il faut en rajouter encore",false,"Le problème n'est pas la quantité de fluide."],["Ce n'est pas important",false,"Il faut revenir à la charge nominale."]]},
   {q:"Pourquoi le filtre s'est-il colmaté ?",o:[["Il faut chercher : humidité, acide, calamine d'une brasure sans azote… et traiter la cause",true,"Le filtre est saturé de particules noires : de la calamine d'une réparation faite sans azote. Tu changes le filtre et tu informes le responsable."],["Les filtres se colmatent tout seuls, sans cause",false,"Un filtre se colmate parce qu'il retient quelque chose : on cherche quoi."],["C'est la faute du fluide R134a",false,"Le fluide n'y est pour rien."]]}],
  fin:"Restriction au filtre déshydrateur (calamine d'une brasure faite sans azote) : BP basse, surchauffe 22 K, sous-refroidissement 12 K. L'ajout de fluide précédent avait surchargé le circuit. Récupération, filtre neuf, vide, charge au poids, explication au responsable.",
  retenir:"Le sous-refroidissement distingue la restriction (élevé) du manque de fluide (faible). Ne jamais « rajouter du fluide » sans diagnostic."},

 {id:"humidite",t:"Le froid s'arrête puis repart tout seul",ic:"💧",niv:3,
  bon:{lieu:"Boucherie — chambre positive R134a, réparée il y a deux semaines par une autre entreprise",qui:"Le boucher",heure:"Vendredi 9 h",prio:2,pb:"La chambre se réchauffe par moments puis le froid revient. La BP chute brutalement par intermittence.",contrainte:"Viande fraîche en stock."},
  etapes:[
   {info:"Le voyant liquide montre une pastille passée au jaune (humidité). Le détendeur givre puis dégivre par cycles.",q:"Hypothèse ?",o:[["De l'humidité dans le circuit qui gèle au détendeur et le bouche par intermittence",true,"Le bouchon de glace se forme à la détente puis fond : la BP chute et remonte."],["Un manque de fluide",false,"Un manque de fluide donnerait des symptômes constants, pas intermittents avec indicateur d'humidité."],["Une panne de thermostat",false,"Le thermostat n'explique pas la chute de BP et l'indicateur jaune."]]},
   {q:"D'où vient probablement cette humidité ?",o:[["D'un tirage au vide insuffisant lors de la réparation précédente",true,"L'humidité de l'air est restée dans le circuit."],["Du fluide neuf",false,"Le fluide neuf est sec."],["De la viande",false,"L'humidité de la chambre ne pénètre pas dans un circuit étanche."]]},
   {q:"Ta réparation :",o:[["Récupérer, remplacer le filtre déshydrateur, tirer un vide poussé et vérifier sa tenue, recharger au poids",true,"Nouveau vide qui tient, charge au poids, la pastille du voyant redevient verte en quelques jours."],["Ajouter un antigel dans le circuit",false,"On n'ajoute pas d'additif : on retire l'humidité."],["Chauffer le détendeur en permanence",false,"Ça masque le symptôme sans traiter la cause."]]},
   {q:"Et l'huile POE du compresseur ?",o:[["Contrôler son acidité : l'humidité avec la POE forme des acides",true,"Test d'acidité légèrement positif : filtre anti-acide posé, recontrôle prévu."],["Elle n'est jamais affectée",false,"La POE est hygroscopique : l'humidité peut la rendre acide."],["La vidanger dans l'évier",false,"L'huile usagée est un déchet à traiter."]]}],
  fin:"Humidité restée dans le circuit après une réparation (vide insuffisant) : glace intermittente au détendeur, indicateur d'humidité jaune, huile légèrement acide. Récupération, filtre neuf + anti-acide, vide poussé contrôlé, charge au poids.",
  retenir:"Le tirage au vide n'est pas une formalité : l'humidité restante bouche le détendeur et rend l'huile acide."},

 {id:"incondensables",t:"La HP est haute même machine arrêtée",ic:"🎈",niv:3,
  bon:{lieu:"Bureau — split R410A remis en service après un déménagement",qui:"Gestionnaire du bâtiment",heure:"Mardi 10 h",prio:2,pb:"Depuis le déménagement, la clim refroidit mal et l'unité extérieure se met en sécurité.",contrainte:"Salle de réunion utilisée l'après-midi."},
  etapes:[
   {info:"Machine arrêtée depuis 2 heures, tout est à 25 °C. Le manomètre indique 18,5 bar. Saturation du R410A à 25 °C : 15,6 bar.",q:"Que signifie une pression supérieure à la saturation, machine à l'arrêt ?",o:[["Il y a des incondensables (air) dans le circuit",true,"Le gaz qui ne se condense pas ajoute sa pression à celle du fluide."],["Un manque de fluide",false,"Un manque donnerait une pression égale ou inférieure à la saturation."],["Que tout va bien",false,"À l'arrêt et à température égale, la pression doit correspondre à la saturation."]]},
   {q:"Comment l'air est-il probablement entré ?",o:[["Les liaisons ont été rouvertes au déménagement sans tirage au vide",true,"Le technicien précédent a reraccordé et ouvert les vannes directement."],["Par le compresseur",false,"Un compresseur ne fabrique pas d'air."],["Par l'évacuation des condensats",false,"Elle n'est pas reliée au circuit frigorifique."]]},
   {q:"Ta réparation :",o:[["Récupérer le fluide, rechercher les fuites, tirer au vide, recharger au poids (fluide neuf ou régénéré selon son état)",true,"Après vide et recharge au poids : HP normale, la clim refroidit."],["Purger un peu de gaz par la vanne HP",false,"C'est un dégazage : interdit, et on perd du fluide."],["Rajouter du fluide",false,"Ça ferait encore monter la HP."]]},
   {q:"Pour finir :",o:[["Fiche d'intervention avec masses récupérée et chargée, BSFF si le fluide part en traitement",true,"Traçabilité complète."],["Rien à noter",false,"Récupération et charge se notent."],["Noter seulement la charge",false,"La masse récupérée doit aussi figurer."]]}],
  fin:"Incondensables (air) introduits lors d'un déplacement sans tirage au vide : pression à l'arrêt supérieure à la saturation, HP trop haute en marche. Récupération, recherche de fuite, vide, recharge au poids, traçabilité.",
  retenir:"Machine à l'arrêt et à température stable : la pression doit correspondre à la saturation. Au-dessus = incondensables."},

 {id:"condensats",t:"L'eau coule de l'unité intérieure",ic:"💦",niv:1,
  bon:{lieu:"Cabinet médical — split cassette au plafond",qui:"Secrétaire",heure:"Jeudi 9 h",prio:2,pb:"De l'eau goutte du plafond, sous la cassette, quand la clim tourne.",contrainte:"Salle d'attente occupée."},
  etapes:[
   {q:"De l'eau sous une cassette en mode froid : piste principale ?",o:[["L'évacuation des condensats (pente, bouchon, pompe de relevage)",true,"La cassette a une pompe de relevage intégrée."],["Une fuite de fluide frigorigène",false,"Le fluide ne coule pas en eau : il s'évapore."],["Le compresseur",false,"Il est dans l'unité extérieure."]]},
   {info:"Le bac est plein. La pompe de relevage ronronne mais ne refoule rien ; son filtre d'aspiration est bouché par des boues.",q:"Que fais-tu ?",o:[["Consigner, nettoyer le bac et le filtre de la pompe, désinfecter, tester la pompe",true,"La pompe refoule à nouveau. Tu vérifies aussi la sécurité de niveau qui doit arrêter la clim si le bac déborde."],["Percer le bac pour que l'eau tombe",false,"Ça ne résout rien et abîme l'appareil."],["Couper la clim définitivement",false,"On répare."]]},
   {q:"Pourquoi l'eau a-t-elle débordé au lieu que la clim s'arrête ?",o:[["La sécurité de niveau (flotteur) était débranchée ou défaillante",true,"Le flotteur était déconnecté. Tu le rebranches et le testes : la clim s'arrête quand le bac est trop plein."],["C'est normal",false,"La sécurité de niveau doit couper avant le débordement."],["À cause du fluide",false,"Le fluide n'a rien à voir."]]}],
  fin:"Pompe de relevage colmatée par des boues et sécurité de niveau déconnectée : débordement du bac de condensats. Nettoyage, désinfection, test de la pompe et de la sécurité. Conseil : entretien annuel du bac et de la pompe.",
  retenir:"Eau qui coule d'une unité intérieure = condensats : pente, bouchon, pompe de relevage, sécurité de niveau."},

 {id:"pac-givre",t:"La PAC n'arrive plus à chauffer en hiver",ic:"❄️",niv:2,
  bon:{lieu:"Maison — PAC air/eau, plancher chauffant",qui:"Mme Faure",heure:"Lundi 8 h, −3 °C dehors",prio:1,pb:"La maison est à 16 °C. L'unité extérieure est couverte de glace.",contrainte:"Personne âgée dans la maison."},
  etapes:[
   {q:"Une unité extérieure prise en glace : que doit faire normalement la PAC ?",o:[["Lancer des dégivrages par inversion de cycle",true,"Tu observes : la PAC ne lance jamais de dégivrage."],["Rien, c'est normal",false,"Un peu de givre est normal, un bloc de glace non : les dégivrages doivent l'éliminer."],["S'arrêter définitivement",false,"Elle doit dégivrer et continuer à chauffer."]]},
   {q:"La PAC ne lance pas ses dégivrages. Que contrôles-tu ?",o:[["La sonde de température de la batterie extérieure et la vanne 4 voies",true,"La sonde de batterie indique +12 °C alors que la batterie est glacée : la sonde est défectueuse, la PAC ne voit pas le givre."],["Le filtre du plancher chauffant",false,"Il n'a rien à voir avec le dégivrage."],["La charge en fluide en premier",false,"On vérifie d'abord la commande du dégivrage."]]},
   {q:"Après remplacement de la sonde, autre chose à vérifier ?",o:[["L'évacuation de l'eau de dégivrage sous l'unité (support surélevé, pas de regel)",true,"L'unité est posée au sol et l'eau regelait dessous. Tu conseilles un support surélevé."],["Rien",false,"Une eau de dégivrage qui regèle sous l'unité bloque à nouveau la batterie."],["La couleur de l'unité",false,"Sans rapport."]]},
   {q:"En attendant que la batterie dégèle :",o:[["Activer l'appoint électrique de la PAC et prévenir la cliente",true,"La maison remonte en température pendant que la PAC dégivre."],["Arroser l'unité à l'eau bouillante",false,"Risque de choc thermique et de dégâts : on laisse dégivrer la machine."],["Casser la glace au marteau",false,"On abîme les ailettes et les tubes."]]}],
  fin:"Sonde de batterie extérieure défectueuse : la PAC ne lançait plus de dégivrages, la batterie s'est prise en glace. Sonde remplacée, appoint activé temporairement, conseil de surélever l'unité pour l'écoulement de l'eau de dégivrage.",
  retenir:"PAC prise en glace : sonde de batterie, vanne 4 voies, évacuation de l'eau de dégivrage."},

 {id:"brulure-moteur",t:"Odeur de brûlé : le compresseur a grillé",ic:"💥",niv:3,
  bon:{lieu:"Supermarché — groupe de condensation d'une chambre positive R134a",qui:"Responsable technique",heure:"Dimanche 18 h",prio:1,pb:"Le disjoncteur du compresseur a sauté, une odeur âcre sort du groupe.",contrainte:"Ouverture du magasin demain 8 h."},
  etapes:[
   {info:"Mesure d'isolement du compresseur (hors tension, au mégohmmètre) : 0 Ω entre une borne et la carcasse.",q:"Conclusion ?",o:[["Le moteur du compresseur est grillé (défaut à la masse)",true,"Le compresseur hermétique est à remplacer."],["Le disjoncteur est trop sensible",false,"Il a déclenché parce qu'il y a un vrai défaut."],["Il manque de l'huile seulement",false,"Un défaut à la masse est électrique : le bobinage est détruit."]]},
   {q:"Avant de remplacer, tu…",o:[["Cherches la cause de la panne (retour de liquide, surchauffe, tension, contacteur)",true,"Tu trouves un contacteur aux contacts soudés sur une phase : le moteur a tourné en monophasé et a grillé."],["Remplaces seulement le compresseur",false,"Si la cause reste, le compresseur neuf grillera aussi."],["Changes de fluide",false,"Sans rapport avec la cause."]]},
   {info:"Le fluide est récupéré. L'huile est noire et sent fort.",q:"Que fais-tu de cette huile ?",o:[["Test d'acidité : il est positif, donc filtre anti-acide sur l'aspiration et la ligne liquide",true,"Les acides de la combustion du bobinage doivent être retirés du circuit."],["Rien, le compresseur neuf a son huile",false,"Les acides restés dans le circuit attaqueraient le compresseur neuf."],["La remettre dans le compresseur neuf",false,"Jamais : elle est contaminée."]]},
   {q:"Après remplacement du compresseur et du contacteur :",o:[["Essai azote, vide poussé, charge au poids, puis recontrôle de l'acidité et remplacement des filtres si besoin",true,"Après 48 h, l'huile est redevenue neutre : les filtres anti-acide sont remplacés par des filtres normaux."],["Démarrer sans faire le vide",false,"L'humidité aggraverait l'acidité."],["Ne rien recontrôler",false,"L'acidité se contrôle après quelques jours de fonctionnement."]]}],
  fin:"Compresseur grillé (défaut à la masse) à cause d'un contacteur aux contacts soudés (fonctionnement en monophasé). Récupération, remplacement du compresseur et du contacteur, filtres anti-acide, vide poussé, charge au poids, suivi de l'acidité.",
  retenir:"Un compresseur grillé laisse de l'acide : test d'acidité, filtre anti-acide, et surtout traitement de la cause."},

 {id:"controle-etancheite",t:"Contrôle d'étanchéité réglementaire",ic:"📋",niv:3,
  bon:{lieu:"Restaurant collectif — chambre froide négative, 12 kg de R404A",qui:"Gestionnaire",heure:"Mardi 14 h",prio:3,pb:"Le gestionnaire demande si son installation est en règle : dernier contrôle il y a 11 mois.",contrainte:"Aucune."},
  etapes:[
   {q:"Combien de t éq. CO₂ représentent 12 kg de R404A (PRP 3 922) ?",o:[["47,1 t éq. CO₂",true,"12 × 3 922 ÷ 1 000 = 47,06."],["4,7 t éq. CO₂",false,"Attention au calcul : 12 × 3 922 = 47 064 kg, soit 47,1 t."],["470 t éq. CO₂",false,"On divise par 1 000 pour passer en tonnes : 47,1 t."]]},
   {q:"Quelle fréquence de contrôle, sans détection permanente ?",o:[["Tous les 12 mois (entre 5 et 50 t)",true,"Le prochain contrôle doit être fait dans le mois."],["Tous les 3 mois",false,"Les 3 mois concernent 500 t éq. CO₂ et plus."],["Aucun contrôle",false,"Au-dessus de 5 t éq. CO₂, le contrôle est obligatoire."]]},
   {q:"Le gestionnaire veut ajouter 4 kg de R404A neuf pour « avoir de la marge ». Ta réponse ?",o:[["Non : on ne surcharge pas, et le fluide neuf à PRP ≥ 2 500 est interdit pour l'entretien",true,"Tu lui expliques aussi qu'à terme, il faudra prévoir une installation avec un fluide à plus faible PRP."],["Oui, sans problème",false,"Surcharger est une erreur, et le R404A neuf est interdit pour l'entretien."],["Oui, mais seulement 2 kg",false,"La charge doit rester la charge nominale ; et le neuf PRP ≥ 2 500 est interdit."]]},
   {info:"Le contrôle ne révèle aucune fuite.",q:"Ce que tu remets au gestionnaire :",o:[["La fiche d'intervention Cerfa 15497*04 (contrôle d'étanchéité) à garder dans le registre",true,"Tout est tracé. Prochain contrôle dans 12 mois."],["Rien, il n'y a pas eu de fuite",false,"Le contrôle d'étanchéité lui-même se trace sur la fiche."],["Un BSFF",false,"Le BSFF concerne le fluide récupéré : ici, aucun fluide n'a été retiré."]]}],
  fin:"Installation de 47,1 t éq. CO₂ : contrôle d'étanchéité tous les 12 mois (sans détection permanente). Contrôle réalisé sans fuite, fiche d'intervention remise, refus d'une surcharge et information sur l'interdiction du R404A neuf pour l'entretien.",
  retenir:"t éq. CO₂ = kg × PRP ÷ 1 000. 5 t → 12 mois, 50 t → 6 mois, 500 t → 3 mois (doublés avec détection)."},

 {id:"mise-au-rebut",t:"Démonter un climatiseur en fin de vie",ic:"♻️",niv:2,
  bon:{lieu:"Commerce — vieux split R410A (2,4 kg) à remplacer",qui:"Commerçant",heure:"Vendredi 8 h",prio:3,pb:"Remplacement de l'ancien split par un modèle neuf au R32.",contrainte:"Le commerce ouvre à 10 h."},
  etapes:[
   {q:"Première opération sur l'ancien split :",o:[["Récupérer tout le fluide avec une station dans une bouteille de récupération R410A",true,"Tu pèses la bouteille vide (tare) avant de commencer."],["Couper les tubes et laisser le fluide s'échapper",false,"C'est un dégazage : strictement interdit."],["Démonter l'unité extérieure chargée",false,"On récupère d'abord le fluide."]]},
   {q:"La bouteille de récupération contient déjà du R32. Tu…",o:[["Prends une autre bouteille, dédiée au R410A",true,"Une bouteille = un seul fluide, sinon le mélange ne peut plus être régénéré."],["Utilises la même, ce sont deux HFC",false,"Jamais de mélange de fluides dans une bouteille."],["Mélanges, ce n'est pas grave",false,"Le mélange coûte cher à détruire et ne peut pas être régénéré."]]},
   {info:"Bouteille de 12,5 kg de capacité, vide. Tu récupères 2,3 kg.",q:"Remplissage autorisé ?",o:[["Oui : 2,3 kg, bien en dessous de 80 % (10 kg)",true,"Il reste de la place pour d'autres récupérations de R410A."],["Non, il faut deux bouteilles",false,"80 % de 12,5 kg = 10 kg : 2,3 kg passe largement."],["Non, une bouteille ne sert qu'une fois",false,"On peut compléter une bouteille avec le même fluide jusqu'à 80 %."]]},
   {q:"Documents à établir :",o:[["Fiche d'intervention (2,3 kg récupérés) et BSFF sur Trackdéchets pour le fluide",true,"La bouteille repart chez le distributeur pour régénération ou destruction."],["Aucun, l'appareil part à la déchetterie",false,"La récupération se trace, le fluide est un déchet dangereux."],["Un permis de construire",false,"Sans rapport."]]}],
  fin:"Récupération de 2,3 kg de R410A dans une bouteille dédiée (jamais de mélange), sous la limite des 80 %. Fiche d'intervention et BSFF sur Trackdéchets. L'appareil vide peut alors être démonté et évacué dans la filière des déchets d'équipements électriques.",
  retenir:"Fin de vie : récupération complète, une bouteille par fluide, 80 % maximum, fiche + BSFF."}
];
